/* hud-gtk.c generated by valac 0.18.0, the Vala compiler
 * generated from hud-gtk.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <hud-client.h>
#include <dee.h>
#include <stdlib.h>
#include <string.h>
#include <gio/gio.h>


#define HUD_GTK_TYPE_CELL_RENDERER_VARIANT (hud_gtk_cell_renderer_variant_get_type ())
#define HUD_GTK_CELL_RENDERER_VARIANT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), HUD_GTK_TYPE_CELL_RENDERER_VARIANT, HudGtkCellRendererVariant))
#define HUD_GTK_CELL_RENDERER_VARIANT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), HUD_GTK_TYPE_CELL_RENDERER_VARIANT, HudGtkCellRendererVariantClass))
#define HUD_GTK_IS_CELL_RENDERER_VARIANT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), HUD_GTK_TYPE_CELL_RENDERER_VARIANT))
#define HUD_GTK_IS_CELL_RENDERER_VARIANT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), HUD_GTK_TYPE_CELL_RENDERER_VARIANT))
#define HUD_GTK_CELL_RENDERER_VARIANT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), HUD_GTK_TYPE_CELL_RENDERER_VARIANT, HudGtkCellRendererVariantClass))

typedef struct _HudGtkCellRendererVariant HudGtkCellRendererVariant;
typedef struct _HudGtkCellRendererVariantClass HudGtkCellRendererVariantClass;
typedef struct _HudGtkCellRendererVariantPrivate HudGtkCellRendererVariantPrivate;
#define _g_free0(var) (var = (g_free (var), NULL))

#define HUD_GTK_TYPE_WINDOW (hud_gtk_window_get_type ())
#define HUD_GTK_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), HUD_GTK_TYPE_WINDOW, HudGtkWindow))
#define HUD_GTK_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), HUD_GTK_TYPE_WINDOW, HudGtkWindowClass))
#define HUD_GTK_IS_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), HUD_GTK_TYPE_WINDOW))
#define HUD_GTK_IS_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), HUD_GTK_TYPE_WINDOW))
#define HUD_GTK_WINDOW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), HUD_GTK_TYPE_WINDOW, HudGtkWindowClass))

typedef struct _HudGtkWindow HudGtkWindow;
typedef struct _HudGtkWindowClass HudGtkWindowClass;
typedef struct _HudGtkWindowPrivate HudGtkWindowPrivate;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_variant_unref0(var) ((var == NULL) ? NULL : (var = (g_variant_unref (var), NULL)))
#define _gtk_tree_path_free0(var) ((var == NULL) ? NULL : (var = (gtk_tree_path_free (var), NULL)))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))

#define HUD_GTK_TYPE_APPLICATION (hud_gtk_application_get_type ())
#define HUD_GTK_APPLICATION(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), HUD_GTK_TYPE_APPLICATION, HudGtkApplication))
#define HUD_GTK_APPLICATION_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), HUD_GTK_TYPE_APPLICATION, HudGtkApplicationClass))
#define HUD_GTK_IS_APPLICATION(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), HUD_GTK_TYPE_APPLICATION))
#define HUD_GTK_IS_APPLICATION_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), HUD_GTK_TYPE_APPLICATION))
#define HUD_GTK_APPLICATION_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), HUD_GTK_TYPE_APPLICATION, HudGtkApplicationClass))

typedef struct _HudGtkApplication HudGtkApplication;
typedef struct _HudGtkApplicationClass HudGtkApplicationClass;
typedef struct _HudGtkApplicationPrivate HudGtkApplicationPrivate;

struct _HudGtkCellRendererVariant {
	GtkCellRendererText parent_instance;
	HudGtkCellRendererVariantPrivate * priv;
};

struct _HudGtkCellRendererVariantClass {
	GtkCellRendererTextClass parent_class;
};

struct _HudGtkWindow {
	GtkApplicationWindow parent_instance;
	HudGtkWindowPrivate * priv;
};

struct _HudGtkWindowClass {
	GtkApplicationWindowClass parent_class;
};

struct _HudGtkWindowPrivate {
	GtkLabel* voice_label;
	GtkListStore* model;
	GtkListStore* appstack_model;
	HudClientQuery* query;
};

struct _HudGtkApplication {
	GtkApplication parent_instance;
	HudGtkApplicationPrivate * priv;
};

struct _HudGtkApplicationClass {
	GtkApplicationClass parent_class;
};


static gpointer hud_gtk_cell_renderer_variant_parent_class = NULL;
static gpointer hud_gtk_window_parent_class = NULL;
static gpointer hud_gtk_application_parent_class = NULL;

GType hud_gtk_cell_renderer_variant_get_type (void) G_GNUC_CONST;
enum  {
	HUD_GTK_CELL_RENDERER_VARIANT_DUMMY_PROPERTY,
	HUD_GTK_CELL_RENDERER_VARIANT_VALUE
};
HudGtkCellRendererVariant* hud_gtk_cell_renderer_variant_new (void);
HudGtkCellRendererVariant* hud_gtk_cell_renderer_variant_construct (GType object_type);
void hud_gtk_cell_renderer_variant_set_value (HudGtkCellRendererVariant* self, GVariant* value);
static void _vala_hud_gtk_cell_renderer_variant_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);
GType hud_gtk_window_get_type (void) G_GNUC_CONST;
#define HUD_GTK_WINDOW_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), HUD_GTK_TYPE_WINDOW, HudGtkWindowPrivate))
enum  {
	HUD_GTK_WINDOW_DUMMY_PROPERTY
};
static void hud_gtk_window_results_row_added (HudGtkWindow* self, DeeModel* results, DeeModelIter* result_iter);
static void hud_gtk_window_results_row_removed (HudGtkWindow* self, DeeModel* results, DeeModelIter* result_iter);
static void hud_gtk_window_appstack_results_row_added (HudGtkWindow* self, DeeModel* results, DeeModelIter* result_iter);
static void hud_gtk_window_appstack_results_row_removed (HudGtkWindow* self, DeeModel* results, DeeModelIter* result_iter);
static void hud_gtk_window_entry_text_changed (HudGtkWindow* self, GObject* object, GParamSpec* pspec);
static void hud_gtk_window_voice_pressed (HudGtkWindow* self, GtkButton* button);
static void hud_gtk_window_view_activated (HudGtkWindow* self, GtkTreeView* view, GtkTreePath* path, GtkTreeViewColumn* column);
static void hud_gtk_window_voice_query_loading (HudGtkWindow* self, HudClientQuery* proxy);
static void hud_gtk_window_voice_query_failed (HudGtkWindow* self, HudClientQuery* proxy, const gchar* cause);
static void hud_gtk_window_voice_query_listening (HudGtkWindow* self, HudClientQuery* proxy);
static void hud_gtk_window_voice_query_heard_something (HudGtkWindow* self, HudClientQuery* proxy);
static void hud_gtk_window_voice_query_finished (HudGtkWindow* self, HudClientQuery* proxy, const gchar* query);
static void hud_gtk_window_appstack_view_activated (HudGtkWindow* self, GtkTreeView* view, GtkTreePath* path, GtkTreeViewColumn* column);
HudGtkWindow* hud_gtk_window_new (GtkApplication* application);
HudGtkWindow* hud_gtk_window_construct (GType object_type, GtkApplication* application);
static void _hud_gtk_window_voice_query_loading_hud_client_query_voice_query_loading (HudClientQuery* _sender, gpointer self);
static void _hud_gtk_window_voice_query_failed_hud_client_query_voice_query_failed (HudClientQuery* _sender, const gchar* object, gpointer self);
static void _hud_gtk_window_voice_query_listening_hud_client_query_voice_query_listening (HudClientQuery* _sender, gpointer self);
static void _hud_gtk_window_voice_query_heard_something_hud_client_query_voice_query_heard_something (HudClientQuery* _sender, gpointer self);
static void _hud_gtk_window_voice_query_finished_hud_client_query_voice_query_finished (HudClientQuery* _sender, const gchar* object, gpointer self);
static void _hud_gtk_window_results_row_added_dee_model_row_added (DeeModel* _sender, DeeModelIter* iter, gpointer self);
static void _hud_gtk_window_results_row_removed_dee_model_row_removed (DeeModel* _sender, DeeModelIter* iter, gpointer self);
static void _hud_gtk_window_appstack_results_row_added_dee_model_row_added (DeeModel* _sender, DeeModelIter* iter, gpointer self);
static void _hud_gtk_window_appstack_results_row_removed_dee_model_row_removed (DeeModel* _sender, DeeModelIter* iter, gpointer self);
static void _hud_gtk_window_entry_text_changed_g_object_notify (GObject* _sender, GParamSpec* pspec, gpointer self);
static void _hud_gtk_window_voice_pressed_gtk_button_clicked (GtkButton* _sender, gpointer self);
static void _hud_gtk_window_view_activated_gtk_tree_view_row_activated (GtkTreeView* _sender, GtkTreePath* path, GtkTreeViewColumn* column, gpointer self);
static void _hud_gtk_window_appstack_view_activated_gtk_tree_view_row_activated (GtkTreeView* _sender, GtkTreePath* path, GtkTreeViewColumn* column, gpointer self);
static void hud_gtk_window_finalize (GObject* obj);
GType hud_gtk_application_get_type (void) G_GNUC_CONST;
enum  {
	HUD_GTK_APPLICATION_DUMMY_PROPERTY
};
static void hud_gtk_application_real_activate (GApplication* base);
HudGtkApplication* hud_gtk_application_new (void);
HudGtkApplication* hud_gtk_application_construct (GType object_type);
gint _vala_main (gchar** args, int args_length1);


HudGtkCellRendererVariant* hud_gtk_cell_renderer_variant_construct (GType object_type) {
	HudGtkCellRendererVariant * self = NULL;
	self = (HudGtkCellRendererVariant*) g_object_new (object_type, NULL);
	return self;
}


HudGtkCellRendererVariant* hud_gtk_cell_renderer_variant_new (void) {
	return hud_gtk_cell_renderer_variant_construct (HUD_GTK_TYPE_CELL_RENDERER_VARIANT);
}


void hud_gtk_cell_renderer_variant_set_value (HudGtkCellRendererVariant* self, GVariant* value) {
	GVariant* _tmp0_;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	if (_tmp0_ != NULL) {
		GVariant* _tmp1_;
		gchar* _tmp2_ = NULL;
		gchar* _tmp3_;
		_tmp1_ = value;
		_tmp2_ = g_variant_print (_tmp1_, FALSE);
		_tmp3_ = _tmp2_;
		g_object_set ((GtkCellRendererText*) self, "text", _tmp3_, NULL);
		_g_free0 (_tmp3_);
	} else {
		g_object_set ((GtkCellRendererText*) self, "text", "(null)", NULL);
	}
	g_object_notify ((GObject *) self, "value");
}


static void hud_gtk_cell_renderer_variant_class_init (HudGtkCellRendererVariantClass * klass) {
	hud_gtk_cell_renderer_variant_parent_class = g_type_class_peek_parent (klass);
	G_OBJECT_CLASS (klass)->set_property = _vala_hud_gtk_cell_renderer_variant_set_property;
	g_object_class_install_property (G_OBJECT_CLASS (klass), HUD_GTK_CELL_RENDERER_VARIANT_VALUE, g_param_spec_variant ("value", "value", "value", G_VARIANT_TYPE_ANY, NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_WRITABLE));
}


static void hud_gtk_cell_renderer_variant_instance_init (HudGtkCellRendererVariant * self) {
}


GType hud_gtk_cell_renderer_variant_get_type (void) {
	static volatile gsize hud_gtk_cell_renderer_variant_type_id__volatile = 0;
	if (g_once_init_enter (&hud_gtk_cell_renderer_variant_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (HudGtkCellRendererVariantClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) hud_gtk_cell_renderer_variant_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (HudGtkCellRendererVariant), 0, (GInstanceInitFunc) hud_gtk_cell_renderer_variant_instance_init, NULL };
		GType hud_gtk_cell_renderer_variant_type_id;
		hud_gtk_cell_renderer_variant_type_id = g_type_register_static (GTK_TYPE_CELL_RENDERER_TEXT, "HudGtkCellRendererVariant", &g_define_type_info, 0);
		g_once_init_leave (&hud_gtk_cell_renderer_variant_type_id__volatile, hud_gtk_cell_renderer_variant_type_id);
	}
	return hud_gtk_cell_renderer_variant_type_id__volatile;
}


static void _vala_hud_gtk_cell_renderer_variant_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	HudGtkCellRendererVariant * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, HUD_GTK_TYPE_CELL_RENDERER_VARIANT, HudGtkCellRendererVariant);
	switch (property_id) {
		case HUD_GTK_CELL_RENDERER_VARIANT_VALUE:
		hud_gtk_cell_renderer_variant_set_value (self, g_value_get_variant (value));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void hud_gtk_window_results_row_added (HudGtkWindow* self, DeeModel* results, DeeModelIter* result_iter) {
	DeeModel* _tmp0_;
	DeeModelIter* _tmp1_;
	guint _tmp2_ = 0U;
	guint pos;
	GtkTreeIter iter = {0};
	GtkListStore* _tmp3_;
	GtkTreeIter _tmp4_ = {0};
	GtkListStore* _tmp5_;
	GtkTreeIter _tmp6_;
	DeeModel* _tmp7_;
	DeeModelIter* _tmp8_;
	const gchar* _tmp9_ = NULL;
	GtkListStore* _tmp10_;
	GtkTreeIter _tmp11_;
	DeeModel* _tmp12_;
	DeeModelIter* _tmp13_;
	const gchar* _tmp14_ = NULL;
	GtkListStore* _tmp15_;
	GtkTreeIter _tmp16_;
	DeeModel* _tmp17_;
	DeeModelIter* _tmp18_;
	const gchar* _tmp19_ = NULL;
	GtkListStore* _tmp20_;
	GtkTreeIter _tmp21_;
	DeeModel* _tmp22_;
	DeeModelIter* _tmp23_;
	const gchar* _tmp24_ = NULL;
	GtkListStore* _tmp25_;
	GtkTreeIter _tmp26_;
	DeeModel* _tmp27_;
	DeeModelIter* _tmp28_;
	GVariant* _tmp29_ = NULL;
	GVariant* _tmp30_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (results != NULL);
	g_return_if_fail (result_iter != NULL);
	_tmp0_ = results;
	_tmp1_ = result_iter;
	_tmp2_ = dee_model_get_position (_tmp0_, _tmp1_);
	pos = _tmp2_;
	_tmp3_ = self->priv->model;
	gtk_list_store_insert (_tmp3_, &_tmp4_, (gint) pos);
	iter = _tmp4_;
	_tmp5_ = self->priv->model;
	_tmp6_ = iter;
	_tmp7_ = results;
	_tmp8_ = result_iter;
	_tmp9_ = dee_model_get_string (_tmp7_, _tmp8_, (guint) 1);
	gtk_list_store_set (_tmp5_, &_tmp6_, 0, _tmp9_, -1);
	_tmp10_ = self->priv->model;
	_tmp11_ = iter;
	_tmp12_ = results;
	_tmp13_ = result_iter;
	_tmp14_ = dee_model_get_string (_tmp12_, _tmp13_, (guint) 3);
	gtk_list_store_set (_tmp10_, &_tmp11_, 1, _tmp14_, -1);
	_tmp15_ = self->priv->model;
	_tmp16_ = iter;
	_tmp17_ = results;
	_tmp18_ = result_iter;
	_tmp19_ = dee_model_get_string (_tmp17_, _tmp18_, (guint) 5);
	gtk_list_store_set (_tmp15_, &_tmp16_, 2, _tmp19_, -1);
	_tmp20_ = self->priv->model;
	_tmp21_ = iter;
	_tmp22_ = results;
	_tmp23_ = result_iter;
	_tmp24_ = dee_model_get_string (_tmp22_, _tmp23_, (guint) 6);
	gtk_list_store_set (_tmp20_, &_tmp21_, 3, _tmp24_, -1);
	_tmp25_ = self->priv->model;
	_tmp26_ = iter;
	_tmp27_ = results;
	_tmp28_ = result_iter;
	_tmp29_ = dee_model_get_value (_tmp27_, _tmp28_, (guint) 0);
	_tmp30_ = _tmp29_;
	gtk_list_store_set (_tmp25_, &_tmp26_, 4, _tmp30_, -1);
	_g_variant_unref0 (_tmp30_);
}


static void hud_gtk_window_results_row_removed (HudGtkWindow* self, DeeModel* results, DeeModelIter* result_iter) {
	DeeModel* _tmp0_;
	DeeModelIter* _tmp1_;
	guint _tmp2_ = 0U;
	guint pos;
	gchar* _tmp3_;
	gchar* spath;
	const gchar* _tmp4_;
	gchar* _tmp5_ = NULL;
	const gchar* _tmp6_;
	GtkTreePath* _tmp7_;
	GtkTreePath* path;
	GtkTreeIter iter = {0};
	GtkListStore* _tmp8_;
	GtkTreeIter _tmp9_ = {0};
	GtkListStore* _tmp10_;
	GtkTreeIter _tmp11_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (results != NULL);
	g_return_if_fail (result_iter != NULL);
	_tmp0_ = results;
	_tmp1_ = result_iter;
	_tmp2_ = dee_model_get_position (_tmp0_, _tmp1_);
	pos = _tmp2_;
	_tmp3_ = g_strdup ("%d");
	spath = _tmp3_;
	_tmp4_ = spath;
	_tmp5_ = g_strdup_printf (_tmp4_, pos);
	_g_free0 (spath);
	spath = _tmp5_;
	_tmp6_ = spath;
	_tmp7_ = gtk_tree_path_new_from_string (_tmp6_);
	path = _tmp7_;
	_tmp8_ = self->priv->model;
	gtk_tree_model_get_iter ((GtkTreeModel*) _tmp8_, &_tmp9_, path);
	iter = _tmp9_;
	_tmp10_ = self->priv->model;
	_tmp11_ = iter;
	gtk_list_store_remove (_tmp10_, &_tmp11_);
	_gtk_tree_path_free0 (path);
	_g_free0 (spath);
}


static void hud_gtk_window_appstack_results_row_added (HudGtkWindow* self, DeeModel* results, DeeModelIter* result_iter) {
	DeeModel* _tmp0_;
	DeeModelIter* _tmp1_;
	guint _tmp2_ = 0U;
	guint pos;
	GtkTreeIter iter = {0};
	GtkListStore* _tmp3_;
	GtkTreeIter _tmp4_ = {0};
	GtkListStore* _tmp5_;
	GtkTreeIter _tmp6_;
	DeeModel* _tmp7_;
	DeeModelIter* _tmp8_;
	const gchar* _tmp9_ = NULL;
	GtkListStore* _tmp10_;
	GtkTreeIter _tmp11_;
	DeeModel* _tmp12_;
	DeeModelIter* _tmp13_;
	const gchar* _tmp14_ = NULL;
	g_return_if_fail (self != NULL);
	g_return_if_fail (results != NULL);
	g_return_if_fail (result_iter != NULL);
	_tmp0_ = results;
	_tmp1_ = result_iter;
	_tmp2_ = dee_model_get_position (_tmp0_, _tmp1_);
	pos = _tmp2_;
	_tmp3_ = self->priv->appstack_model;
	gtk_list_store_insert (_tmp3_, &_tmp4_, (gint) pos);
	iter = _tmp4_;
	_tmp5_ = self->priv->appstack_model;
	_tmp6_ = iter;
	_tmp7_ = results;
	_tmp8_ = result_iter;
	_tmp9_ = dee_model_get_string (_tmp7_, _tmp8_, (guint) 0);
	gtk_list_store_set (_tmp5_, &_tmp6_, 0, _tmp9_, -1);
	_tmp10_ = self->priv->appstack_model;
	_tmp11_ = iter;
	_tmp12_ = results;
	_tmp13_ = result_iter;
	_tmp14_ = dee_model_get_string (_tmp12_, _tmp13_, (guint) 1);
	gtk_list_store_set (_tmp10_, &_tmp11_, 1, _tmp14_, -1);
}


static void hud_gtk_window_appstack_results_row_removed (HudGtkWindow* self, DeeModel* results, DeeModelIter* result_iter) {
	DeeModel* _tmp0_;
	DeeModelIter* _tmp1_;
	guint _tmp2_ = 0U;
	guint pos;
	gchar* _tmp3_;
	gchar* spath;
	const gchar* _tmp4_;
	gchar* _tmp5_ = NULL;
	const gchar* _tmp6_;
	GtkTreePath* _tmp7_;
	GtkTreePath* path;
	GtkTreeIter iter = {0};
	GtkListStore* _tmp8_;
	GtkTreeIter _tmp9_ = {0};
	GtkListStore* _tmp10_;
	GtkTreeIter _tmp11_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (results != NULL);
	g_return_if_fail (result_iter != NULL);
	_tmp0_ = results;
	_tmp1_ = result_iter;
	_tmp2_ = dee_model_get_position (_tmp0_, _tmp1_);
	pos = _tmp2_;
	_tmp3_ = g_strdup ("%d");
	spath = _tmp3_;
	_tmp4_ = spath;
	_tmp5_ = g_strdup_printf (_tmp4_, pos);
	_g_free0 (spath);
	spath = _tmp5_;
	_tmp6_ = spath;
	_tmp7_ = gtk_tree_path_new_from_string (_tmp6_);
	path = _tmp7_;
	_tmp8_ = self->priv->appstack_model;
	gtk_tree_model_get_iter ((GtkTreeModel*) _tmp8_, &_tmp9_, path);
	iter = _tmp9_;
	_tmp10_ = self->priv->appstack_model;
	_tmp11_ = iter;
	gtk_list_store_remove (_tmp10_, &_tmp11_);
	_gtk_tree_path_free0 (path);
	_g_free0 (spath);
}


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


static void hud_gtk_window_entry_text_changed (HudGtkWindow* self, GObject* object, GParamSpec* pspec) {
	GObject* _tmp0_;
	GtkEntry* _tmp1_;
	GtkEntry* entry;
	HudClientQuery* _tmp2_;
	const gchar* _tmp3_;
	const gchar* _tmp4_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (object != NULL);
	g_return_if_fail (pspec != NULL);
	_tmp0_ = object;
	_tmp1_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp0_, GTK_TYPE_ENTRY) ? ((GtkEntry*) _tmp0_) : NULL);
	entry = _tmp1_;
	_tmp2_ = self->priv->query;
	_tmp3_ = gtk_entry_get_text (entry);
	_tmp4_ = _tmp3_;
	hud_client_query_set_query (_tmp2_, _tmp4_);
	_g_object_unref0 (entry);
}


static void hud_gtk_window_voice_pressed (HudGtkWindow* self, GtkButton* button) {
	HudClientQuery* _tmp0_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (button != NULL);
	_tmp0_ = self->priv->query;
	hud_client_query_voice_query (_tmp0_);
}


static void hud_gtk_window_view_activated (HudGtkWindow* self, GtkTreeView* view, GtkTreePath* path, GtkTreeViewColumn* column) {
	GtkTreeIter iter = {0};
	GVariant* key = NULL;
	GtkListStore* _tmp0_;
	GtkTreePath* _tmp1_;
	GtkTreeIter _tmp2_ = {0};
	GtkListStore* _tmp3_;
	GtkTreeIter _tmp4_;
	HudClientQuery* _tmp5_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (view != NULL);
	g_return_if_fail (path != NULL);
	g_return_if_fail (column != NULL);
	_tmp0_ = self->priv->model;
	_tmp1_ = path;
	gtk_tree_model_get_iter ((GtkTreeModel*) _tmp0_, &_tmp2_, _tmp1_);
	iter = _tmp2_;
	_tmp3_ = self->priv->model;
	_tmp4_ = iter;
	gtk_tree_model_get ((GtkTreeModel*) _tmp3_, &_tmp4_, 4, &key, -1);
	_tmp5_ = self->priv->query;
	hud_client_query_execute_command (_tmp5_, key, (guint) 0);
	_g_variant_unref0 (key);
}


static void hud_gtk_window_voice_query_loading (HudGtkWindow* self, HudClientQuery* proxy) {
	GtkLabel* _tmp0_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (proxy != NULL);
	g_debug ("hud-gtk.vala:87: Voice query is loading");
	_tmp0_ = self->priv->voice_label;
	gtk_label_set_label (_tmp0_, "Loading");
}


static void hud_gtk_window_voice_query_failed (HudGtkWindow* self, HudClientQuery* proxy, const gchar* cause) {
	const gchar* _tmp0_;
	GtkLabel* _tmp1_;
	const gchar* _tmp2_;
	GtkMessageDialog* _tmp3_;
	GtkMessageDialog* dialog;
	g_return_if_fail (self != NULL);
	g_return_if_fail (proxy != NULL);
	g_return_if_fail (cause != NULL);
	_tmp0_ = cause;
	g_debug ("hud-gtk.vala:92: Voice query failed, cause=[%s]", _tmp0_);
	_tmp1_ = self->priv->voice_label;
	gtk_label_set_label (_tmp1_, "Idle");
	_tmp2_ = cause;
	_tmp3_ = (GtkMessageDialog*) gtk_message_dialog_new (NULL, GTK_DIALOG_MODAL, GTK_MESSAGE_ERROR, GTK_BUTTONS_OK, "Voice query failed, cause=[%s]", _tmp2_);
	g_object_ref_sink (_tmp3_);
	dialog = _tmp3_;
	gtk_window_set_title ((GtkWindow*) dialog, "Voice query failed");
	gtk_dialog_run ((GtkDialog*) dialog);
	gtk_widget_destroy ((GtkWidget*) dialog);
	_g_object_unref0 (dialog);
}


static void hud_gtk_window_voice_query_listening (HudGtkWindow* self, HudClientQuery* proxy) {
	GtkLabel* _tmp0_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (proxy != NULL);
	g_debug ("hud-gtk.vala:101: Voice query is listening");
	_tmp0_ = self->priv->voice_label;
	gtk_label_set_label (_tmp0_, "Listening");
}


static void hud_gtk_window_voice_query_heard_something (HudGtkWindow* self, HudClientQuery* proxy) {
	GtkLabel* _tmp0_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (proxy != NULL);
	g_debug ("hud-gtk.vala:106: Voice query has heard something");
	_tmp0_ = self->priv->voice_label;
	gtk_label_set_label (_tmp0_, "Heard Something");
}


static void hud_gtk_window_voice_query_finished (HudGtkWindow* self, HudClientQuery* proxy, const gchar* query) {
	const gchar* _tmp0_;
	GtkLabel* _tmp1_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (proxy != NULL);
	g_return_if_fail (query != NULL);
	_tmp0_ = query;
	g_debug ("hud-gtk.vala:111: Voice query is finished, query=[%s]", _tmp0_);
	_tmp1_ = self->priv->voice_label;
	gtk_label_set_label (_tmp1_, "Idle");
}


static void hud_gtk_window_appstack_view_activated (HudGtkWindow* self, GtkTreeView* view, GtkTreePath* path, GtkTreeViewColumn* column) {
	GtkTreeIter iter = {0};
	gchar* key = NULL;
	GtkListStore* _tmp0_;
	GtkTreePath* _tmp1_;
	GtkTreeIter _tmp2_ = {0};
	GtkListStore* _tmp3_;
	GtkTreeIter _tmp4_;
	HudClientQuery* _tmp5_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (view != NULL);
	g_return_if_fail (path != NULL);
	g_return_if_fail (column != NULL);
	_tmp0_ = self->priv->appstack_model;
	_tmp1_ = path;
	gtk_tree_model_get_iter ((GtkTreeModel*) _tmp0_, &_tmp2_, _tmp1_);
	iter = _tmp2_;
	_tmp3_ = self->priv->appstack_model;
	_tmp4_ = iter;
	gtk_tree_model_get ((GtkTreeModel*) _tmp3_, &_tmp4_, 0, &key, -1);
	_tmp5_ = self->priv->query;
	hud_client_query_set_appstack_app (_tmp5_, key);
	_g_free0 (key);
}


static void _hud_gtk_window_voice_query_loading_hud_client_query_voice_query_loading (HudClientQuery* _sender, gpointer self) {
	hud_gtk_window_voice_query_loading (self, _sender);
}


static void _hud_gtk_window_voice_query_failed_hud_client_query_voice_query_failed (HudClientQuery* _sender, const gchar* object, gpointer self) {
	hud_gtk_window_voice_query_failed (self, _sender, object);
}


static void _hud_gtk_window_voice_query_listening_hud_client_query_voice_query_listening (HudClientQuery* _sender, gpointer self) {
	hud_gtk_window_voice_query_listening (self, _sender);
}


static void _hud_gtk_window_voice_query_heard_something_hud_client_query_voice_query_heard_something (HudClientQuery* _sender, gpointer self) {
	hud_gtk_window_voice_query_heard_something (self, _sender);
}


static void _hud_gtk_window_voice_query_finished_hud_client_query_voice_query_finished (HudClientQuery* _sender, const gchar* object, gpointer self) {
	hud_gtk_window_voice_query_finished (self, _sender, object);
}


static void _hud_gtk_window_results_row_added_dee_model_row_added (DeeModel* _sender, DeeModelIter* iter, gpointer self) {
	hud_gtk_window_results_row_added (self, _sender, iter);
}


static void _hud_gtk_window_results_row_removed_dee_model_row_removed (DeeModel* _sender, DeeModelIter* iter, gpointer self) {
	hud_gtk_window_results_row_removed (self, _sender, iter);
}


static void _hud_gtk_window_appstack_results_row_added_dee_model_row_added (DeeModel* _sender, DeeModelIter* iter, gpointer self) {
	hud_gtk_window_appstack_results_row_added (self, _sender, iter);
}


static void _hud_gtk_window_appstack_results_row_removed_dee_model_row_removed (DeeModel* _sender, DeeModelIter* iter, gpointer self) {
	hud_gtk_window_appstack_results_row_removed (self, _sender, iter);
}


static void _hud_gtk_window_entry_text_changed_g_object_notify (GObject* _sender, GParamSpec* pspec, gpointer self) {
	hud_gtk_window_entry_text_changed (self, _sender, pspec);
}


static void _hud_gtk_window_voice_pressed_gtk_button_clicked (GtkButton* _sender, gpointer self) {
	hud_gtk_window_voice_pressed (self, _sender);
}


static void _hud_gtk_window_view_activated_gtk_tree_view_row_activated (GtkTreeView* _sender, GtkTreePath* path, GtkTreeViewColumn* column, gpointer self) {
	hud_gtk_window_view_activated (self, _sender, path, column);
}


static void _hud_gtk_window_appstack_view_activated_gtk_tree_view_row_activated (GtkTreeView* _sender, GtkTreePath* path, GtkTreeViewColumn* column, gpointer self) {
	hud_gtk_window_appstack_view_activated (self, _sender, path, column);
}


HudGtkWindow* hud_gtk_window_construct (GType object_type, GtkApplication* application) {
	HudGtkWindow * self = NULL;
	GtkApplication* _tmp0_;
	GtkBuilder* _tmp1_;
	GtkBuilder* builder;
	GObject* _tmp6_ = NULL;
	GtkLabel* _tmp7_;
	HudClientQuery* _tmp8_;
	HudClientQuery* _tmp9_;
	HudClientQuery* _tmp10_;
	HudClientQuery* _tmp11_;
	HudClientQuery* _tmp12_;
	HudClientQuery* _tmp13_;
	DeeModel* _tmp14_ = NULL;
	DeeModel* _tmp15_;
	DeeModel* results;
	HudClientQuery* _tmp16_;
	DeeModel* _tmp17_ = NULL;
	DeeModel* _tmp18_;
	DeeModel* appstack_results;
	GObject* _tmp19_ = NULL;
	GtkListStore* _tmp20_;
	GObject* _tmp21_ = NULL;
	GObject* _tmp22_ = NULL;
	GObject* _tmp23_ = NULL;
	GObject* _tmp24_ = NULL;
	GObject* _tmp25_ = NULL;
	GtkListStore* _tmp26_;
	GObject* _tmp27_ = NULL;
	GError * _inner_error_ = NULL;
	g_return_val_if_fail (application != NULL, NULL);
	_tmp0_ = application;
	self = (HudGtkWindow*) g_object_new (object_type, "application", _tmp0_, "title", "Hud", NULL);
	gtk_window_set_default_size ((GtkWindow*) self, 500, 300);
	_tmp1_ = gtk_builder_new ();
	builder = _tmp1_;
	{
		HudGtkCellRendererVariant* _tmp2_;
		HudGtkCellRendererVariant* _tmp3_;
		HudClientQuery* _tmp4_;
		_tmp2_ = hud_gtk_cell_renderer_variant_new ();
		g_object_ref_sink (_tmp2_);
		_tmp3_ = _tmp2_;
		_g_object_unref0 (_tmp3_);
		gtk_builder_add_from_file (builder, HUD_GTK_DATADIR "/hud-gtk.ui", &_inner_error_);
		if (_inner_error_ != NULL) {
			goto __catch0_g_error;
		}
		_tmp4_ = hud_client_query_new ("");
		_g_object_unref0 (self->priv->query);
		self->priv->query = _tmp4_;
	}
	goto __finally0;
	__catch0_g_error:
	{
		GError* e = NULL;
		const gchar* _tmp5_;
		e = _inner_error_;
		_inner_error_ = NULL;
		_tmp5_ = e->message;
		g_error ("hud-gtk.vala:135: %s", _tmp5_);
		_g_error_free0 (e);
	}
	__finally0:
	if (_inner_error_ != NULL) {
		_g_object_unref0 (builder);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return NULL;
	}
	_tmp6_ = gtk_builder_get_object (builder, "voice-status");
	_tmp7_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp6_, GTK_TYPE_LABEL) ? ((GtkLabel*) _tmp6_) : NULL);
	_g_object_unref0 (self->priv->voice_label);
	self->priv->voice_label = _tmp7_;
	_tmp8_ = self->priv->query;
	g_signal_connect_object (_tmp8_, "voice-query-loading", (GCallback) _hud_gtk_window_voice_query_loading_hud_client_query_voice_query_loading, self, 0);
	_tmp9_ = self->priv->query;
	g_signal_connect_object (_tmp9_, "voice-query-failed", (GCallback) _hud_gtk_window_voice_query_failed_hud_client_query_voice_query_failed, self, 0);
	_tmp10_ = self->priv->query;
	g_signal_connect_object (_tmp10_, "voice-query-listening", (GCallback) _hud_gtk_window_voice_query_listening_hud_client_query_voice_query_listening, self, 0);
	_tmp11_ = self->priv->query;
	g_signal_connect_object (_tmp11_, "voice-query-heard-something", (GCallback) _hud_gtk_window_voice_query_heard_something_hud_client_query_voice_query_heard_something, self, 0);
	_tmp12_ = self->priv->query;
	g_signal_connect_object (_tmp12_, "voice-query-finished", (GCallback) _hud_gtk_window_voice_query_finished_hud_client_query_voice_query_finished, self, 0);
	_tmp13_ = self->priv->query;
	_tmp14_ = hud_client_query_get_results_model (_tmp13_);
	_tmp15_ = _g_object_ref0 (_tmp14_);
	results = _tmp15_;
	g_signal_connect_object (results, "row-added", (GCallback) _hud_gtk_window_results_row_added_dee_model_row_added, self, 0);
	g_signal_connect_object (results, "row-removed", (GCallback) _hud_gtk_window_results_row_removed_dee_model_row_removed, self, 0);
	_tmp16_ = self->priv->query;
	_tmp17_ = hud_client_query_get_appstack_model (_tmp16_);
	_tmp18_ = _g_object_ref0 (_tmp17_);
	appstack_results = _tmp18_;
	g_signal_connect_object (appstack_results, "row-added", (GCallback) _hud_gtk_window_appstack_results_row_added_dee_model_row_added, self, 0);
	g_signal_connect_object (appstack_results, "row-removed", (GCallback) _hud_gtk_window_appstack_results_row_removed_dee_model_row_removed, self, 0);
	_tmp19_ = gtk_builder_get_object (builder, "liststore");
	_tmp20_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp19_, GTK_TYPE_LIST_STORE) ? ((GtkListStore*) _tmp19_) : NULL);
	_g_object_unref0 (self->priv->model);
	self->priv->model = _tmp20_;
	_tmp21_ = gtk_builder_get_object (builder, "entry");
	g_signal_connect_object (_tmp21_, "notify::text", (GCallback) _hud_gtk_window_entry_text_changed_g_object_notify, self, 0);
	_tmp22_ = gtk_builder_get_object (builder, "voice");
	g_signal_connect_object (G_TYPE_CHECK_INSTANCE_TYPE (_tmp22_, GTK_TYPE_BUTTON) ? ((GtkButton*) _tmp22_) : NULL, "clicked", (GCallback) _hud_gtk_window_voice_pressed_gtk_button_clicked, self, 0);
	_tmp23_ = gtk_builder_get_object (builder, "treeview");
	g_signal_connect_object (G_TYPE_CHECK_INSTANCE_TYPE (_tmp23_, GTK_TYPE_TREE_VIEW) ? ((GtkTreeView*) _tmp23_) : NULL, "row-activated", (GCallback) _hud_gtk_window_view_activated_gtk_tree_view_row_activated, self, 0);
	_tmp24_ = gtk_builder_get_object (builder, "grid");
	gtk_container_add ((GtkContainer*) self, G_TYPE_CHECK_INSTANCE_TYPE (_tmp24_, GTK_TYPE_WIDGET) ? ((GtkWidget*) _tmp24_) : NULL);
	_tmp25_ = gtk_builder_get_object (builder, "appstack_liststore");
	_tmp26_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp25_, GTK_TYPE_LIST_STORE) ? ((GtkListStore*) _tmp25_) : NULL);
	_g_object_unref0 (self->priv->appstack_model);
	self->priv->appstack_model = _tmp26_;
	_tmp27_ = gtk_builder_get_object (builder, "appstack_treeview");
	g_signal_connect_object (G_TYPE_CHECK_INSTANCE_TYPE (_tmp27_, GTK_TYPE_TREE_VIEW) ? ((GtkTreeView*) _tmp27_) : NULL, "row-activated", (GCallback) _hud_gtk_window_appstack_view_activated_gtk_tree_view_row_activated, self, 0);
	_g_object_unref0 (appstack_results);
	_g_object_unref0 (results);
	_g_object_unref0 (builder);
	return self;
}


HudGtkWindow* hud_gtk_window_new (GtkApplication* application) {
	return hud_gtk_window_construct (HUD_GTK_TYPE_WINDOW, application);
}


static void hud_gtk_window_class_init (HudGtkWindowClass * klass) {
	hud_gtk_window_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (HudGtkWindowPrivate));
	G_OBJECT_CLASS (klass)->finalize = hud_gtk_window_finalize;
}


static void hud_gtk_window_instance_init (HudGtkWindow * self) {
	self->priv = HUD_GTK_WINDOW_GET_PRIVATE (self);
}


static void hud_gtk_window_finalize (GObject* obj) {
	HudGtkWindow * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, HUD_GTK_TYPE_WINDOW, HudGtkWindow);
	_g_object_unref0 (self->priv->voice_label);
	_g_object_unref0 (self->priv->model);
	_g_object_unref0 (self->priv->appstack_model);
	_g_object_unref0 (self->priv->query);
	G_OBJECT_CLASS (hud_gtk_window_parent_class)->finalize (obj);
}


GType hud_gtk_window_get_type (void) {
	static volatile gsize hud_gtk_window_type_id__volatile = 0;
	if (g_once_init_enter (&hud_gtk_window_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (HudGtkWindowClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) hud_gtk_window_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (HudGtkWindow), 0, (GInstanceInitFunc) hud_gtk_window_instance_init, NULL };
		GType hud_gtk_window_type_id;
		hud_gtk_window_type_id = g_type_register_static (GTK_TYPE_APPLICATION_WINDOW, "HudGtkWindow", &g_define_type_info, 0);
		g_once_init_leave (&hud_gtk_window_type_id__volatile, hud_gtk_window_type_id);
	}
	return hud_gtk_window_type_id__volatile;
}


static void hud_gtk_application_real_activate (GApplication* base) {
	HudGtkApplication * self;
	HudGtkWindow* _tmp0_;
	HudGtkWindow* _tmp1_;
	self = (HudGtkApplication*) base;
	_tmp0_ = hud_gtk_window_new ((GtkApplication*) self);
	g_object_ref_sink (_tmp0_);
	_tmp1_ = _tmp0_;
	gtk_widget_show_all ((GtkWidget*) _tmp1_);
	_g_object_unref0 (_tmp1_);
}


HudGtkApplication* hud_gtk_application_construct (GType object_type) {
	HudGtkApplication * self = NULL;
	self = (HudGtkApplication*) g_object_new (object_type, "application-id", "com.canonical.HudGtk", NULL);
	return self;
}


HudGtkApplication* hud_gtk_application_new (void) {
	return hud_gtk_application_construct (HUD_GTK_TYPE_APPLICATION);
}


static void hud_gtk_application_class_init (HudGtkApplicationClass * klass) {
	hud_gtk_application_parent_class = g_type_class_peek_parent (klass);
	G_APPLICATION_CLASS (klass)->activate = hud_gtk_application_real_activate;
}


static void hud_gtk_application_instance_init (HudGtkApplication * self) {
}


GType hud_gtk_application_get_type (void) {
	static volatile gsize hud_gtk_application_type_id__volatile = 0;
	if (g_once_init_enter (&hud_gtk_application_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (HudGtkApplicationClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) hud_gtk_application_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (HudGtkApplication), 0, (GInstanceInitFunc) hud_gtk_application_instance_init, NULL };
		GType hud_gtk_application_type_id;
		hud_gtk_application_type_id = g_type_register_static (GTK_TYPE_APPLICATION, "HudGtkApplication", &g_define_type_info, 0);
		g_once_init_leave (&hud_gtk_application_type_id__volatile, hud_gtk_application_type_id);
	}
	return hud_gtk_application_type_id__volatile;
}


gint _vala_main (gchar** args, int args_length1) {
	gint result = 0;
	HudGtkApplication* _tmp0_;
	HudGtkApplication* _tmp1_;
	gchar** _tmp2_;
	gint _tmp2__length1;
	gint _tmp3_ = 0;
	gint _tmp4_;
	_tmp0_ = hud_gtk_application_new ();
	_tmp1_ = _tmp0_;
	_tmp2_ = args;
	_tmp2__length1 = args_length1;
	_tmp3_ = g_application_run ((GApplication*) _tmp1_, _tmp2__length1, _tmp2_);
	_tmp4_ = _tmp3_;
	_g_object_unref0 (_tmp1_);
	result = _tmp4_;
	return result;
}


int main (int argc, char ** argv) {
	g_type_init ();
	return _vala_main (argv, argc);
}



