/* consumer.c generated by valac 0.18.0, the Vala compiler
 * generated from consumer.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <gtk/gtk.h>
#include <gio/gio.h>
#include "yodawgiheardyoulikeactiongroup.h"
#include <gobject/gvaluecollector.h>


#define TYPE_WAITER (waiter_get_type ())
#define WAITER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_WAITER, Waiter))
#define WAITER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_WAITER, WaiterClass))
#define IS_WAITER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_WAITER))
#define IS_WAITER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_WAITER))
#define WAITER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_WAITER, WaiterClass))

typedef struct _Waiter Waiter;
typedef struct _WaiterClass WaiterClass;
typedef struct _WaiterPrivate WaiterPrivate;
typedef struct _ParamSpecWaiter ParamSpecWaiter;
#define _waiter_unref0(var) ((var == NULL) ? NULL : (var = (waiter_unref (var), NULL)))
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_variant_unref0(var) ((var == NULL) ? NULL : (var = (g_variant_unref (var), NULL)))

struct _Waiter {
	GTypeInstance parent_instance;
	volatile int ref_count;
	WaiterPrivate * priv;
};

struct _WaiterClass {
	GTypeClass parent_class;
	void (*finalize) (Waiter *self);
};

struct _WaiterPrivate {
	gboolean done;
};

struct _ParamSpecWaiter {
	GParamSpec parent_instance;
};


static gpointer waiter_parent_class = NULL;

gpointer waiter_ref (gpointer instance);
void waiter_unref (gpointer instance);
GParamSpec* param_spec_waiter (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void value_set_waiter (GValue* value, gpointer v_object);
void value_take_waiter (GValue* value, gpointer v_object);
gpointer value_get_waiter (const GValue* value);
GType waiter_get_type (void) G_GNUC_CONST;
#define WAITER_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TYPE_WAITER, WaiterPrivate))
enum  {
	WAITER_DUMMY_PROPERTY
};
static gboolean waiter_cb (Waiter* self);
Waiter* waiter_new (guint ms);
Waiter* waiter_construct (GType object_type, guint ms);
static gboolean _waiter_cb_gsource_func (gpointer self);
static void waiter_finalize (Waiter* obj);
#define operation_one "[{'type': <'slider'>, 'action': <'op.radius'>, 'label': <'Radius'>, 'r" \
"ange': <(0.0, 100.0)>}, {'type': <'toggle'>, 'action': <'op.gaussian'>" \
", 'label': <'Gaussian'>}, {'type': <'button'>, 'action': <'op.apply'>," \
" 'label': <'Apply'>}]"
#define operation_two "[{'type': <'slider'>, 'action': <'op.red'>, 'label': <'Red'>, 'range':" \
" <(0, 255)>}, {'type': <'slider'>, 'action': <'op.green'>, 'label': <'" \
"Green'>, 'range': <(0, 255)>}, {'type': <'slider'>, 'action': <'op.blu" \
"e'>, 'label': <'Blue'>, 'range': <(0, 255)>}, {'type': <'button'>, 'ac" \
"tion': <'op.apply'>, 'label': <'Apply'>}]"
void _vala_main (gchar** args, int args_length1);
GtkWidget* gv_tk_create (GVariant* items, GActionGroup* actions);


static gboolean waiter_cb (Waiter* self) {
	gboolean result = FALSE;
	g_return_val_if_fail (self != NULL, FALSE);
	self->priv->done = TRUE;
	result = FALSE;
	return result;
}


static gboolean _waiter_cb_gsource_func (gpointer self) {
	gboolean result;
	result = waiter_cb (self);
	return result;
}


Waiter* waiter_construct (GType object_type, guint ms) {
	Waiter* self = NULL;
	guint _tmp0_;
	self = (Waiter*) g_type_create_instance (object_type);
	_tmp0_ = ms;
	g_timeout_add_full (G_PRIORITY_DEFAULT, _tmp0_, _waiter_cb_gsource_func, waiter_ref (self), waiter_unref);
	while (TRUE) {
		gboolean _tmp1_;
		_tmp1_ = self->priv->done;
		if (!(!_tmp1_)) {
			break;
		}
		g_main_context_iteration ((GMainContext*) NULL, TRUE);
	}
	return self;
}


Waiter* waiter_new (guint ms) {
	return waiter_construct (TYPE_WAITER, ms);
}


static void value_waiter_init (GValue* value) {
	value->data[0].v_pointer = NULL;
}


static void value_waiter_free_value (GValue* value) {
	if (value->data[0].v_pointer) {
		waiter_unref (value->data[0].v_pointer);
	}
}


static void value_waiter_copy_value (const GValue* src_value, GValue* dest_value) {
	if (src_value->data[0].v_pointer) {
		dest_value->data[0].v_pointer = waiter_ref (src_value->data[0].v_pointer);
	} else {
		dest_value->data[0].v_pointer = NULL;
	}
}


static gpointer value_waiter_peek_pointer (const GValue* value) {
	return value->data[0].v_pointer;
}


static gchar* value_waiter_collect_value (GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	if (collect_values[0].v_pointer) {
		Waiter* object;
		object = collect_values[0].v_pointer;
		if (object->parent_instance.g_class == NULL) {
			return g_strconcat ("invalid unclassed object pointer for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		} else if (!g_value_type_compatible (G_TYPE_FROM_INSTANCE (object), G_VALUE_TYPE (value))) {
			return g_strconcat ("invalid object type `", g_type_name (G_TYPE_FROM_INSTANCE (object)), "' for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		}
		value->data[0].v_pointer = waiter_ref (object);
	} else {
		value->data[0].v_pointer = NULL;
	}
	return NULL;
}


static gchar* value_waiter_lcopy_value (const GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	Waiter** object_p;
	object_p = collect_values[0].v_pointer;
	if (!object_p) {
		return g_strdup_printf ("value location for `%s' passed as NULL", G_VALUE_TYPE_NAME (value));
	}
	if (!value->data[0].v_pointer) {
		*object_p = NULL;
	} else if (collect_flags & G_VALUE_NOCOPY_CONTENTS) {
		*object_p = value->data[0].v_pointer;
	} else {
		*object_p = waiter_ref (value->data[0].v_pointer);
	}
	return NULL;
}


GParamSpec* param_spec_waiter (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags) {
	ParamSpecWaiter* spec;
	g_return_val_if_fail (g_type_is_a (object_type, TYPE_WAITER), NULL);
	spec = g_param_spec_internal (G_TYPE_PARAM_OBJECT, name, nick, blurb, flags);
	G_PARAM_SPEC (spec)->value_type = object_type;
	return G_PARAM_SPEC (spec);
}


gpointer value_get_waiter (const GValue* value) {
	g_return_val_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_WAITER), NULL);
	return value->data[0].v_pointer;
}


void value_set_waiter (GValue* value, gpointer v_object) {
	Waiter* old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_WAITER));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, TYPE_WAITER));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
		waiter_ref (value->data[0].v_pointer);
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		waiter_unref (old);
	}
}


void value_take_waiter (GValue* value, gpointer v_object) {
	Waiter* old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_WAITER));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, TYPE_WAITER));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		waiter_unref (old);
	}
}


static void waiter_class_init (WaiterClass * klass) {
	waiter_parent_class = g_type_class_peek_parent (klass);
	WAITER_CLASS (klass)->finalize = waiter_finalize;
	g_type_class_add_private (klass, sizeof (WaiterPrivate));
}


static void waiter_instance_init (Waiter * self) {
	self->priv = WAITER_GET_PRIVATE (self);
	self->ref_count = 1;
}


static void waiter_finalize (Waiter* obj) {
	Waiter * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_WAITER, Waiter);
}


GType waiter_get_type (void) {
	static volatile gsize waiter_type_id__volatile = 0;
	if (g_once_init_enter (&waiter_type_id__volatile)) {
		static const GTypeValueTable g_define_type_value_table = { value_waiter_init, value_waiter_free_value, value_waiter_copy_value, value_waiter_peek_pointer, "p", value_waiter_collect_value, "p", value_waiter_lcopy_value };
		static const GTypeInfo g_define_type_info = { sizeof (WaiterClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) waiter_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (Waiter), 0, (GInstanceInitFunc) waiter_instance_init, &g_define_type_value_table };
		static const GTypeFundamentalInfo g_define_type_fundamental_info = { (G_TYPE_FLAG_CLASSED | G_TYPE_FLAG_INSTANTIATABLE | G_TYPE_FLAG_DERIVABLE | G_TYPE_FLAG_DEEP_DERIVABLE) };
		GType waiter_type_id;
		waiter_type_id = g_type_register_fundamental (g_type_fundamental_next (), "Waiter", &g_define_type_info, &g_define_type_fundamental_info, 0);
		g_once_init_leave (&waiter_type_id__volatile, waiter_type_id);
	}
	return waiter_type_id__volatile;
}


gpointer waiter_ref (gpointer instance) {
	Waiter* self;
	self = instance;
	g_atomic_int_inc (&self->ref_count);
	return instance;
}


void waiter_unref (gpointer instance) {
	Waiter* self;
	self = instance;
	if (g_atomic_int_dec_and_test (&self->ref_count)) {
		WAITER_GET_CLASS (self)->finalize (self);
		g_type_free_instance ((GTypeInstance *) self);
	}
}


void _vala_main (gchar** args, int args_length1) {
	GDBusConnection* _tmp0_ = NULL;
	GDBusConnection* bus;
	GDBusConnection* _tmp1_;
	gchar** _tmp2_;
	gint _tmp2__length1;
	const gchar* _tmp3_;
	GDBusActionGroup* _tmp4_ = NULL;
	GDBusActionGroup* group;
	GDBusActionGroup* _tmp5_;
	Waiter* _tmp6_;
	Waiter* _tmp7_;
	GtkWindow* _tmp8_;
	GtkWindow* window;
	GDBusActionGroup* _tmp9_;
	GActionGroup* _tmp10_ = NULL;
	GActionGroup* yodawg;
	GVariant* _tmp11_ = NULL;
	GVariant* _tmp12_;
	GtkWindow* _tmp13_;
	GVariant* _tmp14_;
	GActionGroup* _tmp15_;
	GtkWidget* _tmp16_ = NULL;
	GtkWidget* _tmp17_;
	GtkWindow* _tmp18_;
	GError * _inner_error_ = NULL;
	gtk_init (&args_length1, &args);
	_tmp0_ = g_bus_get_sync (G_BUS_TYPE_SESSION, NULL, &_inner_error_);
	bus = _tmp0_;
	if (_inner_error_ != NULL) {
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	_tmp1_ = bus;
	_tmp2_ = args;
	_tmp2__length1 = args_length1;
	_tmp3_ = _tmp2_[1];
	_tmp4_ = g_dbus_action_group_get (_tmp1_, _tmp3_, "/org/gtk/Application/anonymous");
	group = _tmp4_;
	_tmp5_ = group;
	g_action_group_has_action ((GActionGroup*) _tmp5_, "foo");
	_tmp6_ = waiter_new ((guint) 100);
	_tmp7_ = _tmp6_;
	_waiter_unref0 (_tmp7_);
	_tmp8_ = (GtkWindow*) gtk_window_new (GTK_WINDOW_TOPLEVEL);
	g_object_ref_sink (_tmp8_);
	window = _tmp8_;
	_tmp9_ = group;
	_tmp10_ = yo_dawg_i_heard_you_like_action_group_start ((GActionGroup*) _tmp9_, "blur", NULL);
	yodawg = _tmp10_;
	_tmp11_ = g_variant_parse (NULL, operation_one, NULL, NULL, &_inner_error_);
	_tmp12_ = _tmp11_;
	if (_inner_error_ != NULL) {
		_g_object_unref0 (yodawg);
		_g_object_unref0 (window);
		_g_object_unref0 (group);
		_g_object_unref0 (bus);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	_tmp13_ = window;
	_tmp14_ = _tmp12_;
	_tmp15_ = yodawg;
	_tmp16_ = gv_tk_create (_tmp14_, _tmp15_);
	_tmp17_ = _tmp16_;
	gtk_container_add ((GtkContainer*) _tmp13_, _tmp17_);
	_g_object_unref0 (_tmp17_);
	_g_variant_unref0 (_tmp14_);
	_tmp18_ = window;
	gtk_widget_show_all ((GtkWidget*) _tmp18_);
	_g_object_unref0 (yodawg);
	yodawg = NULL;
	gtk_main ();
	_g_object_unref0 (yodawg);
	_g_object_unref0 (window);
	_g_object_unref0 (group);
	_g_object_unref0 (bus);
}


int main (int argc, char ** argv) {
	g_type_init ();
	_vala_main (argv, argc);
	return 0;
}



