/* gvtk.c generated by valac 0.18.0, the Vala compiler
 * generated from gvtk.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <stdlib.h>
#include <string.h>
#include <gio/gio.h>

#define _g_variant_unref0(var) ((var == NULL) ? NULL : (var = (g_variant_unref (var), NULL)))
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_variant_iter_free0(var) ((var == NULL) ? NULL : (var = (g_variant_iter_free (var), NULL)))
#define _g_variant_type_free0(var) ((var == NULL) ? NULL : (var = (g_variant_type_free (var), NULL)))



void gtk_widget_insert_action_group (GtkWidget* widget, const gchar* name, GActionGroup* group);
GtkWidget* gv_tk_create (GVariant* items, GActionGroup* actions);
void gv_tk_create_slider (GtkWidget** left, GtkWidget** right, GVariant* item, GActionGroup* actions);
void gv_tk_create_button (GtkWidget** left, GtkWidget** right, GVariant* item, GActionGroup* actions);
void gv_tk_create_toggle (GtkWidget** left, GtkWidget** right, GVariant* item, GActionGroup* actions);
GtkWidget* gv_tk_create_label (GVariant* item);


GtkWidget* gv_tk_create (GVariant* items, GActionGroup* actions) {
	GtkWidget* result = NULL;
	GtkGrid* _tmp0_;
	GtkGrid* grid;
	GtkGrid* _tmp1_;
	GActionGroup* _tmp2_;
	GtkGrid* _tmp35_;
	g_return_val_if_fail (items != NULL, NULL);
	_tmp0_ = (GtkGrid*) gtk_grid_new ();
	g_object_ref_sink (_tmp0_);
	grid = _tmp0_;
	_tmp1_ = grid;
	_tmp2_ = actions;
	gtk_widget_insert_action_group ((GtkWidget*) _tmp1_, "op", _tmp2_);
	{
		GVariant* _tmp3_;
		GVariantIter* _tmp4_ = NULL;
		GVariantIter* _item_it;
		GVariant* item = NULL;
		_tmp3_ = items;
		_tmp4_ = g_variant_iter_new (_tmp3_);
		_item_it = _tmp4_;
		while (TRUE) {
			GVariantIter* _tmp5_;
			GVariant* _tmp6_ = NULL;
			GVariant* _tmp7_;
			GVariant* _tmp8_;
			const GVariantType* _tmp9_;
			GVariant* _tmp10_ = NULL;
			GVariant* type;
			GVariant* _tmp11_;
			GtkWidget* left = NULL;
			GtkWidget* right = NULL;
			GVariant* _tmp12_;
			const gchar* _tmp13_ = NULL;
			const gchar* _tmp14_;
			GQuark _tmp16_ = 0U;
			static GQuark _tmp15_label0 = 0;
			static GQuark _tmp15_label1 = 0;
			static GQuark _tmp15_label2 = 0;
			GtkGrid* _tmp29_;
			GtkWidget* _tmp30_;
			GtkWidget* _tmp31_;
			_tmp5_ = _item_it;
			_tmp6_ = g_variant_iter_next_value (_tmp5_);
			_g_variant_unref0 (item);
			item = _tmp6_;
			_tmp7_ = item;
			if (!(_tmp7_ != NULL)) {
				break;
			}
			_tmp8_ = item;
			_tmp9_ = G_VARIANT_TYPE_STRING;
			_tmp10_ = g_variant_lookup_value (_tmp8_, "type", _tmp9_);
			type = _tmp10_;
			_tmp11_ = type;
			if (_tmp11_ == NULL) {
				_g_variant_unref0 (type);
				continue;
			}
			_tmp12_ = type;
			_tmp13_ = g_variant_get_string (_tmp12_, NULL);
			_tmp14_ = _tmp13_;
			_tmp16_ = (NULL == _tmp14_) ? 0 : g_quark_from_string (_tmp14_);
			if (_tmp16_ == ((0 != _tmp15_label0) ? _tmp15_label0 : (_tmp15_label0 = g_quark_from_static_string ("slider")))) {
				switch (0) {
					default:
					{
						GVariant* _tmp17_;
						GActionGroup* _tmp18_;
						GtkWidget* _tmp19_ = NULL;
						GtkWidget* _tmp20_ = NULL;
						_tmp17_ = item;
						_tmp18_ = actions;
						gv_tk_create_slider (&_tmp19_, &_tmp20_, _tmp17_, _tmp18_);
						_g_object_unref0 (left);
						left = _tmp19_;
						_g_object_unref0 (right);
						right = _tmp20_;
						break;
					}
				}
			} else if (_tmp16_ == ((0 != _tmp15_label1) ? _tmp15_label1 : (_tmp15_label1 = g_quark_from_static_string ("button")))) {
				switch (0) {
					default:
					{
						GVariant* _tmp21_;
						GActionGroup* _tmp22_;
						GtkWidget* _tmp23_ = NULL;
						GtkWidget* _tmp24_ = NULL;
						_tmp21_ = item;
						_tmp22_ = actions;
						gv_tk_create_button (&_tmp23_, &_tmp24_, _tmp21_, _tmp22_);
						_g_object_unref0 (left);
						left = _tmp23_;
						_g_object_unref0 (right);
						right = _tmp24_;
						break;
					}
				}
			} else if (_tmp16_ == ((0 != _tmp15_label2) ? _tmp15_label2 : (_tmp15_label2 = g_quark_from_static_string ("toggle")))) {
				switch (0) {
					default:
					{
						GVariant* _tmp25_;
						GActionGroup* _tmp26_;
						GtkWidget* _tmp27_ = NULL;
						GtkWidget* _tmp28_ = NULL;
						_tmp25_ = item;
						_tmp26_ = actions;
						gv_tk_create_toggle (&_tmp27_, &_tmp28_, _tmp25_, _tmp26_);
						_g_object_unref0 (left);
						left = _tmp27_;
						_g_object_unref0 (right);
						right = _tmp28_;
						break;
					}
				}
			} else {
				switch (0) {
					default:
					{
						continue;
					}
				}
			}
			_tmp29_ = grid;
			_tmp30_ = right;
			gtk_grid_attach_next_to (_tmp29_, _tmp30_, NULL, GTK_POS_BOTTOM, 1, 1);
			_tmp31_ = left;
			if (_tmp31_ != NULL) {
				GtkGrid* _tmp32_;
				GtkWidget* _tmp33_;
				GtkWidget* _tmp34_;
				_tmp32_ = grid;
				_tmp33_ = left;
				_tmp34_ = right;
				gtk_grid_attach_next_to (_tmp32_, _tmp33_, _tmp34_, GTK_POS_LEFT, 1, 1);
			}
			_g_object_unref0 (right);
			_g_object_unref0 (left);
			_g_variant_unref0 (type);
		}
		_g_variant_unref0 (item);
		_g_variant_iter_free0 (_item_it);
	}
	_tmp35_ = grid;
	gtk_widget_show_all ((GtkWidget*) _tmp35_);
	result = (GtkWidget*) grid;
	return result;
}


GtkWidget* gv_tk_create_label (GVariant* item) {
	GtkWidget* result = NULL;
	GVariant* _tmp0_;
	const GVariantType* _tmp1_;
	GVariant* _tmp2_ = NULL;
	GVariant* label;
	const gchar* _tmp3_ = NULL;
	GVariant* _tmp4_;
	const gchar* _tmp7_;
	GtkLabel* _tmp8_;
	g_return_val_if_fail (item != NULL, NULL);
	_tmp0_ = item;
	_tmp1_ = G_VARIANT_TYPE_STRING;
	_tmp2_ = g_variant_lookup_value (_tmp0_, "label", _tmp1_);
	label = _tmp2_;
	_tmp4_ = label;
	if (_tmp4_ != NULL) {
		GVariant* _tmp5_;
		const gchar* _tmp6_ = NULL;
		_tmp5_ = label;
		_tmp6_ = g_variant_get_string (_tmp5_, NULL);
		_tmp3_ = _tmp6_;
	} else {
		_tmp3_ = "";
	}
	_tmp7_ = _tmp3_;
	_tmp8_ = (GtkLabel*) gtk_label_new (_tmp7_);
	g_object_ref_sink (_tmp8_);
	result = (GtkWidget*) _tmp8_;
	_g_variant_unref0 (label);
	return result;
}


void gv_tk_create_slider (GtkWidget** left, GtkWidget** right, GVariant* item, GActionGroup* actions) {
	GtkWidget* _vala_left = NULL;
	GtkWidget* _vala_right = NULL;
	GVariant* _tmp0_;
	GVariantType* _tmp1_;
	GVariantType* _tmp2_;
	GVariant* _tmp3_ = NULL;
	GVariant* _tmp4_;
	GVariant* range;
	GVariant* _tmp5_;
	const GVariantType* _tmp6_;
	GVariant* _tmp7_ = NULL;
	GVariant* action;
	GtkScale* _tmp8_;
	GVariant* _tmp9_;
	GtkWidget* _tmp10_ = NULL;
	g_return_if_fail (item != NULL);
	_tmp0_ = item;
	_tmp1_ = g_variant_type_new ("(**)");
	_tmp2_ = _tmp1_;
	_tmp3_ = g_variant_lookup_value (_tmp0_, "range", _tmp2_);
	_tmp4_ = _tmp3_;
	_g_variant_type_free0 (_tmp2_);
	range = _tmp4_;
	_tmp5_ = item;
	_tmp6_ = G_VARIANT_TYPE_STRING;
	_tmp7_ = g_variant_lookup_value (_tmp5_, "action", _tmp6_);
	action = _tmp7_;
	_tmp8_ = (GtkScale*) gtk_scale_new (GTK_ORIENTATION_HORIZONTAL, NULL);
	g_object_ref_sink (_tmp8_);
	_g_object_unref0 (_vala_right);
	_vala_right = (GtkWidget*) _tmp8_;
	_tmp9_ = item;
	_tmp10_ = gv_tk_create_label (_tmp9_);
	_g_object_unref0 (_vala_left);
	_vala_left = _tmp10_;
	gtk_widget_set_hexpand (_vala_right, TRUE);
	_g_variant_unref0 (action);
	_g_variant_unref0 (range);
	if (left) {
		*left = _vala_left;
	} else {
		_g_object_unref0 (_vala_left);
	}
	if (right) {
		*right = _vala_right;
	} else {
		_g_object_unref0 (_vala_right);
	}
}


void gv_tk_create_button (GtkWidget** left, GtkWidget** right, GVariant* item, GActionGroup* actions) {
	GtkWidget* _vala_left = NULL;
	GtkWidget* _vala_right = NULL;
	GVariant* _tmp0_;
	const GVariantType* _tmp1_;
	GVariant* _tmp2_ = NULL;
	GVariant* action;
	GVariant* _tmp3_;
	const GVariantType* _tmp4_;
	GVariant* _tmp5_ = NULL;
	GVariant* label;
	const gchar* _tmp6_ = NULL;
	GVariant* _tmp7_;
	const gchar* _tmp10_;
	GtkButton* _tmp11_;
	GVariant* _tmp12_;
	const gchar* _tmp13_ = NULL;
	g_return_if_fail (item != NULL);
	_tmp0_ = item;
	_tmp1_ = G_VARIANT_TYPE_STRING;
	_tmp2_ = g_variant_lookup_value (_tmp0_, "action", _tmp1_);
	action = _tmp2_;
	_tmp3_ = item;
	_tmp4_ = G_VARIANT_TYPE_STRING;
	_tmp5_ = g_variant_lookup_value (_tmp3_, "label", _tmp4_);
	label = _tmp5_;
	_tmp7_ = label;
	if (_tmp7_ != NULL) {
		GVariant* _tmp8_;
		const gchar* _tmp9_ = NULL;
		_tmp8_ = label;
		_tmp9_ = g_variant_get_string (_tmp8_, NULL);
		_tmp6_ = _tmp9_;
	} else {
		_tmp6_ = "";
	}
	_tmp10_ = _tmp6_;
	_tmp11_ = (GtkButton*) gtk_button_new_with_label (_tmp10_);
	g_object_ref_sink (_tmp11_);
	_g_object_unref0 (_vala_right);
	_vala_right = (GtkWidget*) _tmp11_;
	_tmp12_ = action;
	_tmp13_ = g_variant_get_string (_tmp12_, NULL);
	gtk_actionable_set_action_name ((GtkActionable*) (G_TYPE_CHECK_INSTANCE_TYPE (_vala_right, GTK_TYPE_BUTTON) ? ((GtkButton*) _vala_right) : NULL), _tmp13_);
	_g_object_unref0 (_vala_left);
	_vala_left = NULL;
	_g_variant_unref0 (label);
	_g_variant_unref0 (action);
	if (left) {
		*left = _vala_left;
	} else {
		_g_object_unref0 (_vala_left);
	}
	if (right) {
		*right = _vala_right;
	} else {
		_g_object_unref0 (_vala_right);
	}
}


void gv_tk_create_toggle (GtkWidget** left, GtkWidget** right, GVariant* item, GActionGroup* actions) {
	GtkWidget* _vala_left = NULL;
	GtkWidget* _vala_right = NULL;
	GVariant* _tmp0_;
	const GVariantType* _tmp1_;
	GVariant* _tmp2_ = NULL;
	GVariant* action;
	GtkCheckButton* _tmp3_;
	GVariant* _tmp4_;
	GtkWidget* _tmp5_ = NULL;
	const gchar* _tmp6_ = NULL;
	g_return_if_fail (item != NULL);
	_tmp0_ = item;
	_tmp1_ = G_VARIANT_TYPE_STRING;
	_tmp2_ = g_variant_lookup_value (_tmp0_, "action", _tmp1_);
	action = _tmp2_;
	_tmp3_ = (GtkCheckButton*) gtk_check_button_new ();
	g_object_ref_sink (_tmp3_);
	_g_object_unref0 (_vala_right);
	_vala_right = (GtkWidget*) _tmp3_;
	_tmp4_ = item;
	_tmp5_ = gv_tk_create_label (_tmp4_);
	_g_object_unref0 (_vala_left);
	_vala_left = _tmp5_;
	_tmp6_ = g_variant_get_string (action, NULL);
	gtk_actionable_set_action_name ((GtkActionable*) (G_TYPE_CHECK_INSTANCE_TYPE (_vala_right, GTK_TYPE_BUTTON) ? ((GtkButton*) _vala_right) : NULL), _tmp6_);
	gtk_widget_set_hexpand (_vala_right, TRUE);
	_g_variant_unref0 (action);
	if (left) {
		*left = _vala_left;
	} else {
		_g_object_unref0 (_vala_left);
	}
	if (right) {
		*right = _vala_right;
	} else {
		_g_object_unref0 (_vala_right);
	}
}



