/*
 * Generated by gdbus-codegen 2.34.1. DO NOT EDIT.
 *
 * The license of this code is the same as for the source it was derived from.
 */

#ifdef HAVE_CONFIG_H
#  include "config.h"
#endif

#include "service-iface.h"

#include <string.h>
#ifdef G_OS_UNIX
#  include <gio/gunixfdlist.h>
#endif

typedef struct
{
  GDBusArgInfo parent_struct;
  gboolean use_gvariant;
} _ExtendedGDBusArgInfo;

typedef struct
{
  GDBusMethodInfo parent_struct;
  const gchar *signal_name;
  gboolean pass_fdlist;
} _ExtendedGDBusMethodInfo;

typedef struct
{
  GDBusSignalInfo parent_struct;
  const gchar *signal_name;
} _ExtendedGDBusSignalInfo;

typedef struct
{
  GDBusPropertyInfo parent_struct;
  const gchar *hyphen_name;
  gboolean use_gvariant;
} _ExtendedGDBusPropertyInfo;

typedef struct
{
  GDBusInterfaceInfo parent_struct;
  const gchar *hyphen_name;
} _ExtendedGDBusInterfaceInfo;

typedef struct
{
  const _ExtendedGDBusPropertyInfo *info;
  guint prop_id;
  GValue orig_value; /* the value before the change */
} ChangedProperty;

static void
_changed_property_free (ChangedProperty *data)
{
  g_value_unset (&data->orig_value);
  g_free (data);
}

static gboolean
_g_strv_equal0 (gchar **a, gchar **b)
{
  gboolean ret = FALSE;
  guint n;
  if (a == NULL && b == NULL)
    {
      ret = TRUE;
      goto out;
    }
  if (a == NULL || b == NULL)
    goto out;
  if (g_strv_length (a) != g_strv_length (b))
    goto out;
  for (n = 0; a[n] != NULL; n++)
    if (g_strcmp0 (a[n], b[n]) != 0)
      goto out;
  ret = TRUE;
out:
  return ret;
}

static gboolean
_g_variant_equal0 (GVariant *a, GVariant *b)
{
  gboolean ret = FALSE;
  if (a == NULL && b == NULL)
    {
      ret = TRUE;
      goto out;
    }
  if (a == NULL || b == NULL)
    goto out;
  ret = g_variant_equal (a, b);
out:
  return ret;
}

G_GNUC_UNUSED static gboolean
_g_value_equal (const GValue *a, const GValue *b)
{
  gboolean ret = FALSE;
  g_assert (G_VALUE_TYPE (a) == G_VALUE_TYPE (b));
  switch (G_VALUE_TYPE (a))
    {
      case G_TYPE_BOOLEAN:
        ret = (g_value_get_boolean (a) == g_value_get_boolean (b));
        break;
      case G_TYPE_UCHAR:
        ret = (g_value_get_uchar (a) == g_value_get_uchar (b));
        break;
      case G_TYPE_INT:
        ret = (g_value_get_int (a) == g_value_get_int (b));
        break;
      case G_TYPE_UINT:
        ret = (g_value_get_uint (a) == g_value_get_uint (b));
        break;
      case G_TYPE_INT64:
        ret = (g_value_get_int64 (a) == g_value_get_int64 (b));
        break;
      case G_TYPE_UINT64:
        ret = (g_value_get_uint64 (a) == g_value_get_uint64 (b));
        break;
      case G_TYPE_DOUBLE:
        {
          /* Avoid -Wfloat-equal warnings by doing a direct bit compare */
          gdouble da = g_value_get_double (a);
          gdouble db = g_value_get_double (b);
          ret = memcmp (&da, &db, sizeof (gdouble)) == 0;
        }
        break;
      case G_TYPE_STRING:
        ret = (g_strcmp0 (g_value_get_string (a), g_value_get_string (b)) == 0);
        break;
      case G_TYPE_VARIANT:
        ret = _g_variant_equal0 (g_value_get_variant (a), g_value_get_variant (b));
        break;
      default:
        if (G_VALUE_TYPE (a) == G_TYPE_STRV)
          ret = _g_strv_equal0 (g_value_get_boxed (a), g_value_get_boxed (b));
        else
          g_critical ("_g_value_equal() does not handle type %s", g_type_name (G_VALUE_TYPE (a)));
        break;
    }
  return ret;
}

/* ------------------------------------------------------------------------
 * Code for interface com.canonical.hud
 * ------------------------------------------------------------------------
 */

/**
 * SECTION:_HudServiceIfaceComCanonicalHud
 * @title: _HudServiceIfaceComCanonicalHud
 * @short_description: Generated C code for the com.canonical.hud D-Bus interface
 *
 * This section contains code for working with the <link linkend="gdbus-interface-com-canonical-hud.top_of_page">com.canonical.hud</link> D-Bus interface in C.
 */

/* ---- Introspection data for com.canonical.hud ---- */

static const _ExtendedGDBusArgInfo __hud_service_iface_com_canonical_hud_method_info_start_query_IN_ARG_query =
{
  {
    -1,
    (gchar *) "query",
    (gchar *) "s",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const __hud_service_iface_com_canonical_hud_method_info_start_query_IN_ARG_pointers[] =
{
  &__hud_service_iface_com_canonical_hud_method_info_start_query_IN_ARG_query,
  NULL
};

static const _ExtendedGDBusArgInfo __hud_service_iface_com_canonical_hud_method_info_start_query_OUT_ARG_queryObject =
{
  {
    -1,
    (gchar *) "queryObject",
    (gchar *) "o",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo __hud_service_iface_com_canonical_hud_method_info_start_query_OUT_ARG_resultsName =
{
  {
    -1,
    (gchar *) "resultsName",
    (gchar *) "s",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo __hud_service_iface_com_canonical_hud_method_info_start_query_OUT_ARG_appstackName =
{
  {
    -1,
    (gchar *) "appstackName",
    (gchar *) "s",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo __hud_service_iface_com_canonical_hud_method_info_start_query_OUT_ARG_modelRevision =
{
  {
    -1,
    (gchar *) "modelRevision",
    (gchar *) "i",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const __hud_service_iface_com_canonical_hud_method_info_start_query_OUT_ARG_pointers[] =
{
  &__hud_service_iface_com_canonical_hud_method_info_start_query_OUT_ARG_queryObject,
  &__hud_service_iface_com_canonical_hud_method_info_start_query_OUT_ARG_resultsName,
  &__hud_service_iface_com_canonical_hud_method_info_start_query_OUT_ARG_appstackName,
  &__hud_service_iface_com_canonical_hud_method_info_start_query_OUT_ARG_modelRevision,
  NULL
};

static const _ExtendedGDBusMethodInfo __hud_service_iface_com_canonical_hud_method_info_start_query =
{
  {
    -1,
    (gchar *) "StartQuery",
    (GDBusArgInfo **) &__hud_service_iface_com_canonical_hud_method_info_start_query_IN_ARG_pointers,
    (GDBusArgInfo **) &__hud_service_iface_com_canonical_hud_method_info_start_query_OUT_ARG_pointers,
    NULL
  },
  "handle-start-query",
  FALSE
};

static const _ExtendedGDBusArgInfo __hud_service_iface_com_canonical_hud_method_info_register_application_IN_ARG_id =
{
  {
    -1,
    (gchar *) "id",
    (gchar *) "s",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const __hud_service_iface_com_canonical_hud_method_info_register_application_IN_ARG_pointers[] =
{
  &__hud_service_iface_com_canonical_hud_method_info_register_application_IN_ARG_id,
  NULL
};

static const _ExtendedGDBusArgInfo __hud_service_iface_com_canonical_hud_method_info_register_application_OUT_ARG_appObject =
{
  {
    -1,
    (gchar *) "appObject",
    (gchar *) "o",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const __hud_service_iface_com_canonical_hud_method_info_register_application_OUT_ARG_pointers[] =
{
  &__hud_service_iface_com_canonical_hud_method_info_register_application_OUT_ARG_appObject,
  NULL
};

static const _ExtendedGDBusMethodInfo __hud_service_iface_com_canonical_hud_method_info_register_application =
{
  {
    -1,
    (gchar *) "RegisterApplication",
    (GDBusArgInfo **) &__hud_service_iface_com_canonical_hud_method_info_register_application_IN_ARG_pointers,
    (GDBusArgInfo **) &__hud_service_iface_com_canonical_hud_method_info_register_application_OUT_ARG_pointers,
    NULL
  },
  "handle-register-application",
  FALSE
};

static const _ExtendedGDBusMethodInfo * const __hud_service_iface_com_canonical_hud_method_info_pointers[] =
{
  &__hud_service_iface_com_canonical_hud_method_info_start_query,
  &__hud_service_iface_com_canonical_hud_method_info_register_application,
  NULL
};

static const _ExtendedGDBusPropertyInfo __hud_service_iface_com_canonical_hud_property_info_open_queries =
{
  {
    -1,
    (gchar *) "OpenQueries",
    (gchar *) "ao",
    G_DBUS_PROPERTY_INFO_FLAGS_READABLE,
    NULL
  },
  "open-queries",
  FALSE
};

static const _ExtendedGDBusPropertyInfo __hud_service_iface_com_canonical_hud_property_info_applications =
{
  {
    -1,
    (gchar *) "Applications",
    (gchar *) "a(so)",
    G_DBUS_PROPERTY_INFO_FLAGS_READABLE,
    NULL
  },
  "applications",
  FALSE
};

static const _ExtendedGDBusPropertyInfo * const __hud_service_iface_com_canonical_hud_property_info_pointers[] =
{
  &__hud_service_iface_com_canonical_hud_property_info_open_queries,
  &__hud_service_iface_com_canonical_hud_property_info_applications,
  NULL
};

static const _ExtendedGDBusInterfaceInfo __hud_service_iface_com_canonical_hud_interface_info =
{
  {
    -1,
    (gchar *) "com.canonical.hud",
    (GDBusMethodInfo **) &__hud_service_iface_com_canonical_hud_method_info_pointers,
    NULL,
    (GDBusPropertyInfo **) &__hud_service_iface_com_canonical_hud_property_info_pointers,
    NULL
  },
  "com-canonical-hud",
};


/**
 * _hud_service_iface_com_canonical_hud_interface_info:
 *
 * Gets a machine-readable description of the <link linkend="gdbus-interface-com-canonical-hud.top_of_page">com.canonical.hud</link> D-Bus interface.
 *
 * Returns: (transfer none): A #GDBusInterfaceInfo. Do not free.
 */
GDBusInterfaceInfo *
_hud_service_iface_com_canonical_hud_interface_info (void)
{
  return (GDBusInterfaceInfo *) &__hud_service_iface_com_canonical_hud_interface_info.parent_struct;
}

/**
 * _hud_service_iface_com_canonical_hud_override_properties:
 * @klass: The class structure for a #GObject<!-- -->-derived class.
 * @property_id_begin: The property id to assign to the first overridden property.
 *
 * Overrides all #GObject properties in the #_HudServiceIfaceComCanonicalHud interface for a concrete class.
 * The properties are overridden in the order they are defined.
 *
 * Returns: The last property id.
 */
guint
_hud_service_iface_com_canonical_hud_override_properties (GObjectClass *klass, guint property_id_begin)
{
  g_object_class_override_property (klass, property_id_begin++, "open-queries");
  g_object_class_override_property (klass, property_id_begin++, "applications");
  return property_id_begin - 1;
}



/**
 * _HudServiceIfaceComCanonicalHud:
 *
 * Abstract interface type for the D-Bus interface <link linkend="gdbus-interface-com-canonical-hud.top_of_page">com.canonical.hud</link>.
 */

/**
 * _HudServiceIfaceComCanonicalHudIface:
 * @parent_iface: The parent interface.
 * @handle_register_application: Handler for the #_HudServiceIfaceComCanonicalHud::handle-register-application signal.
 * @handle_start_query: Handler for the #_HudServiceIfaceComCanonicalHud::handle-start-query signal.
 * @get_applications: Getter for the #_HudServiceIfaceComCanonicalHud:applications property.
 * @get_open_queries: Getter for the #_HudServiceIfaceComCanonicalHud:open-queries property.
 *
 * Virtual table for the D-Bus interface <link linkend="gdbus-interface-com-canonical-hud.top_of_page">com.canonical.hud</link>.
 */

static void
_hud_service_iface_com_canonical_hud_default_init (_HudServiceIfaceComCanonicalHudIface *iface)
{
  /* GObject signals for incoming D-Bus method calls: */
  /**
   * _HudServiceIfaceComCanonicalHud::handle-start-query:
   * @object: A #_HudServiceIfaceComCanonicalHud.
   * @invocation: A #GDBusMethodInvocation.
   * @arg_query: Argument passed by remote caller.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-com-canonical-hud.StartQuery">StartQuery()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call _hud_service_iface_com_canonical_hud_complete_start_query() or e.g. g_dbus_method_invocation_return_error() on it) and no order signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %TRUE if the invocation was handled, %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-start-query",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (_HudServiceIfaceComCanonicalHudIface, handle_start_query),
    g_signal_accumulator_true_handled,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    2,
    G_TYPE_DBUS_METHOD_INVOCATION, G_TYPE_STRING);

  /**
   * _HudServiceIfaceComCanonicalHud::handle-register-application:
   * @object: A #_HudServiceIfaceComCanonicalHud.
   * @invocation: A #GDBusMethodInvocation.
   * @arg_id: Argument passed by remote caller.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-com-canonical-hud.RegisterApplication">RegisterApplication()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call _hud_service_iface_com_canonical_hud_complete_register_application() or e.g. g_dbus_method_invocation_return_error() on it) and no order signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %TRUE if the invocation was handled, %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-register-application",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (_HudServiceIfaceComCanonicalHudIface, handle_register_application),
    g_signal_accumulator_true_handled,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    2,
    G_TYPE_DBUS_METHOD_INVOCATION, G_TYPE_STRING);

  /* GObject properties for D-Bus properties: */
  /**
   * _HudServiceIfaceComCanonicalHud:open-queries:
   *
   * Represents the D-Bus property <link linkend="gdbus-property-com-canonical-hud.OpenQueries">"OpenQueries"</link>.
   *
   * Since the D-Bus property for this #GObject property is readable but not writable, it is meaningful to read from it on both the client- and service-side. It is only meaningful, however, to write to it on the service-side.
   */
  g_object_interface_install_property (iface,
    g_param_spec_boxed ("open-queries", "OpenQueries", "OpenQueries", G_TYPE_STRV, G_PARAM_READWRITE | G_PARAM_STATIC_STRINGS));
  /**
   * _HudServiceIfaceComCanonicalHud:applications:
   *
   * Represents the D-Bus property <link linkend="gdbus-property-com-canonical-hud.Applications">"Applications"</link>.
   *
   * Since the D-Bus property for this #GObject property is readable but not writable, it is meaningful to read from it on both the client- and service-side. It is only meaningful, however, to write to it on the service-side.
   */
  g_object_interface_install_property (iface,
    g_param_spec_variant ("applications", "Applications", "Applications", G_VARIANT_TYPE ("a(so)"), NULL, G_PARAM_READWRITE | G_PARAM_STATIC_STRINGS));
}

typedef _HudServiceIfaceComCanonicalHudIface _HudServiceIfaceComCanonicalHudInterface;
G_DEFINE_INTERFACE (_HudServiceIfaceComCanonicalHud, _hud_service_iface_com_canonical_hud, G_TYPE_OBJECT);

/**
 * _hud_service_iface_com_canonical_hud_get_open_queries: (skip)
 * @object: A #_HudServiceIfaceComCanonicalHud.
 *
 * Gets the value of the <link linkend="gdbus-property-com-canonical-hud.OpenQueries">"OpenQueries"</link> D-Bus property.
 *
 * Since this D-Bus property is readable, it is meaningful to use this function on both the client- and service-side.
 *
 * <warning>The returned value is only valid until the property changes so on the client-side it is only safe to use this function on the thread where @object was constructed. Use _hud_service_iface_com_canonical_hud_dup_open_queries() if on another thread.</warning>
 *
 * Returns: (transfer none): The property value or %NULL if the property is not set. Do not free the returned value, it belongs to @object.
 */
const gchar *const *
_hud_service_iface_com_canonical_hud_get_open_queries (_HudServiceIfaceComCanonicalHud *object)
{
  return _HUD_SERVICE_IFACE_COM_CANONICAL_HUD_GET_IFACE (object)->get_open_queries (object);
}

/**
 * _hud_service_iface_com_canonical_hud_dup_open_queries: (skip)
 * @object: A #_HudServiceIfaceComCanonicalHud.
 *
 * Gets a copy of the <link linkend="gdbus-property-com-canonical-hud.OpenQueries">"OpenQueries"</link> D-Bus property.
 *
 * Since this D-Bus property is readable, it is meaningful to use this function on both the client- and service-side.
 *
 * Returns: (transfer full): The property value or %NULL if the property is not set. The returned value should be freed with g_strfreev().
 */
gchar **
_hud_service_iface_com_canonical_hud_dup_open_queries (_HudServiceIfaceComCanonicalHud *object)
{
  gchar **value;
  g_object_get (G_OBJECT (object), "open-queries", &value, NULL);
  return value;
}

/**
 * _hud_service_iface_com_canonical_hud_set_open_queries: (skip)
 * @object: A #_HudServiceIfaceComCanonicalHud.
 * @value: The value to set.
 *
 * Sets the <link linkend="gdbus-property-com-canonical-hud.OpenQueries">"OpenQueries"</link> D-Bus property to @value.
 *
 * Since this D-Bus property is not writable, it is only meaningful to use this function on the service-side.
 */
void
_hud_service_iface_com_canonical_hud_set_open_queries (_HudServiceIfaceComCanonicalHud *object, const gchar *const *value)
{
  g_object_set (G_OBJECT (object), "open-queries", value, NULL);
}

/**
 * _hud_service_iface_com_canonical_hud_get_applications: (skip)
 * @object: A #_HudServiceIfaceComCanonicalHud.
 *
 * Gets the value of the <link linkend="gdbus-property-com-canonical-hud.Applications">"Applications"</link> D-Bus property.
 *
 * Since this D-Bus property is readable, it is meaningful to use this function on both the client- and service-side.
 *
 * <warning>The returned value is only valid until the property changes so on the client-side it is only safe to use this function on the thread where @object was constructed. Use _hud_service_iface_com_canonical_hud_dup_applications() if on another thread.</warning>
 *
 * Returns: (transfer none): The property value or %NULL if the property is not set. Do not free the returned value, it belongs to @object.
 */
GVariant *
_hud_service_iface_com_canonical_hud_get_applications (_HudServiceIfaceComCanonicalHud *object)
{
  return _HUD_SERVICE_IFACE_COM_CANONICAL_HUD_GET_IFACE (object)->get_applications (object);
}

/**
 * _hud_service_iface_com_canonical_hud_dup_applications: (skip)
 * @object: A #_HudServiceIfaceComCanonicalHud.
 *
 * Gets a copy of the <link linkend="gdbus-property-com-canonical-hud.Applications">"Applications"</link> D-Bus property.
 *
 * Since this D-Bus property is readable, it is meaningful to use this function on both the client- and service-side.
 *
 * Returns: (transfer full): The property value or %NULL if the property is not set. The returned value should be freed with g_variant_unref().
 */
GVariant *
_hud_service_iface_com_canonical_hud_dup_applications (_HudServiceIfaceComCanonicalHud *object)
{
  GVariant *value;
  g_object_get (G_OBJECT (object), "applications", &value, NULL);
  return value;
}

/**
 * _hud_service_iface_com_canonical_hud_set_applications: (skip)
 * @object: A #_HudServiceIfaceComCanonicalHud.
 * @value: The value to set.
 *
 * Sets the <link linkend="gdbus-property-com-canonical-hud.Applications">"Applications"</link> D-Bus property to @value.
 *
 * Since this D-Bus property is not writable, it is only meaningful to use this function on the service-side.
 */
void
_hud_service_iface_com_canonical_hud_set_applications (_HudServiceIfaceComCanonicalHud *object, GVariant *value)
{
  g_object_set (G_OBJECT (object), "applications", value, NULL);
}

/**
 * _hud_service_iface_com_canonical_hud_call_start_query:
 * @proxy: A #_HudServiceIfaceComCanonicalHudProxy.
 * @arg_query: Argument to pass with the method invocation.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-com-canonical-hud.StartQuery">StartQuery()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call _hud_service_iface_com_canonical_hud_call_start_query_finish() to get the result of the operation.
 *
 * See _hud_service_iface_com_canonical_hud_call_start_query_sync() for the synchronous, blocking version of this method.
 */
void
_hud_service_iface_com_canonical_hud_call_start_query (
    _HudServiceIfaceComCanonicalHud *proxy,
    const gchar *arg_query,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "StartQuery",
    g_variant_new ("(s)",
                   arg_query),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * _hud_service_iface_com_canonical_hud_call_start_query_finish:
 * @proxy: A #_HudServiceIfaceComCanonicalHudProxy.
 * @out_queryObject: (out): Return location for return parameter or %NULL to ignore.
 * @out_resultsName: (out): Return location for return parameter or %NULL to ignore.
 * @out_appstackName: (out): Return location for return parameter or %NULL to ignore.
 * @out_modelRevision: (out): Return location for return parameter or %NULL to ignore.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to _hud_service_iface_com_canonical_hud_call_start_query().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with _hud_service_iface_com_canonical_hud_call_start_query().
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
_hud_service_iface_com_canonical_hud_call_start_query_finish (
    _HudServiceIfaceComCanonicalHud *proxy,
    gchar **out_queryObject,
    gchar **out_resultsName,
    gchar **out_appstackName,
    gint *out_modelRevision,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(ossi)",
                 out_queryObject,
                 out_resultsName,
                 out_appstackName,
                 out_modelRevision);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * _hud_service_iface_com_canonical_hud_call_start_query_sync:
 * @proxy: A #_HudServiceIfaceComCanonicalHudProxy.
 * @arg_query: Argument to pass with the method invocation.
 * @out_queryObject: (out): Return location for return parameter or %NULL to ignore.
 * @out_resultsName: (out): Return location for return parameter or %NULL to ignore.
 * @out_appstackName: (out): Return location for return parameter or %NULL to ignore.
 * @out_modelRevision: (out): Return location for return parameter or %NULL to ignore.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-com-canonical-hud.StartQuery">StartQuery()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See _hud_service_iface_com_canonical_hud_call_start_query() for the asynchronous version of this method.
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
_hud_service_iface_com_canonical_hud_call_start_query_sync (
    _HudServiceIfaceComCanonicalHud *proxy,
    const gchar *arg_query,
    gchar **out_queryObject,
    gchar **out_resultsName,
    gchar **out_appstackName,
    gint *out_modelRevision,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "StartQuery",
    g_variant_new ("(s)",
                   arg_query),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(ossi)",
                 out_queryObject,
                 out_resultsName,
                 out_appstackName,
                 out_modelRevision);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * _hud_service_iface_com_canonical_hud_call_register_application:
 * @proxy: A #_HudServiceIfaceComCanonicalHudProxy.
 * @arg_id: Argument to pass with the method invocation.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-com-canonical-hud.RegisterApplication">RegisterApplication()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call _hud_service_iface_com_canonical_hud_call_register_application_finish() to get the result of the operation.
 *
 * See _hud_service_iface_com_canonical_hud_call_register_application_sync() for the synchronous, blocking version of this method.
 */
void
_hud_service_iface_com_canonical_hud_call_register_application (
    _HudServiceIfaceComCanonicalHud *proxy,
    const gchar *arg_id,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "RegisterApplication",
    g_variant_new ("(s)",
                   arg_id),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * _hud_service_iface_com_canonical_hud_call_register_application_finish:
 * @proxy: A #_HudServiceIfaceComCanonicalHudProxy.
 * @out_appObject: (out): Return location for return parameter or %NULL to ignore.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to _hud_service_iface_com_canonical_hud_call_register_application().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with _hud_service_iface_com_canonical_hud_call_register_application().
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
_hud_service_iface_com_canonical_hud_call_register_application_finish (
    _HudServiceIfaceComCanonicalHud *proxy,
    gchar **out_appObject,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(o)",
                 out_appObject);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * _hud_service_iface_com_canonical_hud_call_register_application_sync:
 * @proxy: A #_HudServiceIfaceComCanonicalHudProxy.
 * @arg_id: Argument to pass with the method invocation.
 * @out_appObject: (out): Return location for return parameter or %NULL to ignore.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-com-canonical-hud.RegisterApplication">RegisterApplication()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See _hud_service_iface_com_canonical_hud_call_register_application() for the asynchronous version of this method.
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
_hud_service_iface_com_canonical_hud_call_register_application_sync (
    _HudServiceIfaceComCanonicalHud *proxy,
    const gchar *arg_id,
    gchar **out_appObject,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "RegisterApplication",
    g_variant_new ("(s)",
                   arg_id),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(o)",
                 out_appObject);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * _hud_service_iface_com_canonical_hud_complete_start_query:
 * @object: A #_HudServiceIfaceComCanonicalHud.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 * @queryObject: Parameter to return.
 * @resultsName: Parameter to return.
 * @appstackName: Parameter to return.
 * @modelRevision: Parameter to return.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-com-canonical-hud.StartQuery">StartQuery()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
_hud_service_iface_com_canonical_hud_complete_start_query (
    _HudServiceIfaceComCanonicalHud *object,
    GDBusMethodInvocation *invocation,
    const gchar *queryObject,
    const gchar *resultsName,
    const gchar *appstackName,
    gint modelRevision)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("(ossi)",
                   queryObject,
                   resultsName,
                   appstackName,
                   modelRevision));
}

/**
 * _hud_service_iface_com_canonical_hud_complete_register_application:
 * @object: A #_HudServiceIfaceComCanonicalHud.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 * @appObject: Parameter to return.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-com-canonical-hud.RegisterApplication">RegisterApplication()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
_hud_service_iface_com_canonical_hud_complete_register_application (
    _HudServiceIfaceComCanonicalHud *object,
    GDBusMethodInvocation *invocation,
    const gchar *appObject)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("(o)",
                   appObject));
}

/* ------------------------------------------------------------------------ */

/**
 * _HudServiceIfaceComCanonicalHudProxy:
 *
 * The #_HudServiceIfaceComCanonicalHudProxy structure contains only private data and should only be accessed using the provided API.
 */

/**
 * _HudServiceIfaceComCanonicalHudProxyClass:
 * @parent_class: The parent class.
 *
 * Class structure for #_HudServiceIfaceComCanonicalHudProxy.
 */

struct __HudServiceIfaceComCanonicalHudProxyPrivate
{
  GData *qdata;
};

static void _hud_service_iface_com_canonical_hud_proxy_iface_init (_HudServiceIfaceComCanonicalHudIface *iface);

G_DEFINE_TYPE_WITH_CODE (_HudServiceIfaceComCanonicalHudProxy, _hud_service_iface_com_canonical_hud_proxy, G_TYPE_DBUS_PROXY,
                         G_IMPLEMENT_INTERFACE (_HUD_SERVICE_IFACE_TYPE_COM_CANONICAL_HUD, _hud_service_iface_com_canonical_hud_proxy_iface_init));

static void
_hud_service_iface_com_canonical_hud_proxy_finalize (GObject *object)
{
  _HudServiceIfaceComCanonicalHudProxy *proxy = _HUD_SERVICE_IFACE_COM_CANONICAL_HUD_PROXY (object);
  g_datalist_clear (&proxy->priv->qdata);
  G_OBJECT_CLASS (_hud_service_iface_com_canonical_hud_proxy_parent_class)->finalize (object);
}

static void
_hud_service_iface_com_canonical_hud_proxy_get_property (GObject      *object,
  guint         prop_id,
  GValue       *value,
  GParamSpec   *pspec)
{
  const _ExtendedGDBusPropertyInfo *info;
  GVariant *variant;
  g_assert (prop_id != 0 && prop_id - 1 < 2);
  info = __hud_service_iface_com_canonical_hud_property_info_pointers[prop_id - 1];
  variant = g_dbus_proxy_get_cached_property (G_DBUS_PROXY (object), info->parent_struct.name);
  if (info->use_gvariant)
    {
      g_value_set_variant (value, variant);
    }
  else
    {
      if (variant != NULL)
        g_dbus_gvariant_to_gvalue (variant, value);
    }
  if (variant != NULL)
    g_variant_unref (variant);
}

static void
_hud_service_iface_com_canonical_hud_proxy_set_property_cb (GDBusProxy *proxy,
  GAsyncResult *res,
  gpointer      user_data)
{
  const _ExtendedGDBusPropertyInfo *info = user_data;
  GError *error;
  error = NULL;
  if (!g_dbus_proxy_call_finish (proxy, res, &error))
    {
      g_warning ("Error setting property `%s' on interface com.canonical.hud: %s (%s, %d)",
                 info->parent_struct.name, 
                 error->message, g_quark_to_string (error->domain), error->code);
      g_error_free (error);
    }
}

static void
_hud_service_iface_com_canonical_hud_proxy_set_property (GObject      *object,
  guint         prop_id,
  const GValue *value,
  GParamSpec   *pspec)
{
  const _ExtendedGDBusPropertyInfo *info;
  GVariant *variant;
  g_assert (prop_id != 0 && prop_id - 1 < 2);
  info = __hud_service_iface_com_canonical_hud_property_info_pointers[prop_id - 1];
  variant = g_dbus_gvalue_to_gvariant (value, G_VARIANT_TYPE (info->parent_struct.signature));
  g_dbus_proxy_call (G_DBUS_PROXY (object),
    "org.freedesktop.DBus.Properties.Set",
    g_variant_new ("(ssv)", "com.canonical.hud", info->parent_struct.name, variant),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    NULL, (GAsyncReadyCallback) _hud_service_iface_com_canonical_hud_proxy_set_property_cb, (GDBusPropertyInfo *) &info->parent_struct);
  g_variant_unref (variant);
}

static void
_hud_service_iface_com_canonical_hud_proxy_g_signal (GDBusProxy *proxy,
  const gchar *sender_name,
  const gchar *signal_name,
  GVariant *parameters)
{
  _ExtendedGDBusSignalInfo *info;
  GVariantIter iter;
  GVariant *child;
  GValue *paramv;
  guint num_params;
  guint n;
  guint signal_id;
  info = (_ExtendedGDBusSignalInfo *) g_dbus_interface_info_lookup_signal ((GDBusInterfaceInfo *) &__hud_service_iface_com_canonical_hud_interface_info.parent_struct, signal_name);
  if (info == NULL)
    return;
  num_params = g_variant_n_children (parameters);
  paramv = g_new0 (GValue, num_params + 1);
  g_value_init (&paramv[0], _HUD_SERVICE_IFACE_TYPE_COM_CANONICAL_HUD);
  g_value_set_object (&paramv[0], proxy);
  g_variant_iter_init (&iter, parameters);
  n = 1;
  while ((child = g_variant_iter_next_value (&iter)) != NULL)
    {
      _ExtendedGDBusArgInfo *arg_info = (_ExtendedGDBusArgInfo *) info->parent_struct.args[n - 1];
      if (arg_info->use_gvariant)
        {
          g_value_init (&paramv[n], G_TYPE_VARIANT);
          g_value_set_variant (&paramv[n], child);
          n++;
        }
      else
        g_dbus_gvariant_to_gvalue (child, &paramv[n++]);
      g_variant_unref (child);
    }
  signal_id = g_signal_lookup (info->signal_name, _HUD_SERVICE_IFACE_TYPE_COM_CANONICAL_HUD);
  g_signal_emitv (paramv, signal_id, 0, NULL);
  for (n = 0; n < num_params + 1; n++)
    g_value_unset (&paramv[n]);
  g_free (paramv);
}

static void
_hud_service_iface_com_canonical_hud_proxy_g_properties_changed (GDBusProxy *_proxy,
  GVariant *changed_properties,
  const gchar *const *invalidated_properties)
{
  _HudServiceIfaceComCanonicalHudProxy *proxy = _HUD_SERVICE_IFACE_COM_CANONICAL_HUD_PROXY (_proxy);
  guint n;
  const gchar *key;
  GVariantIter *iter;
  _ExtendedGDBusPropertyInfo *info;
  g_variant_get (changed_properties, "a{sv}", &iter);
  while (g_variant_iter_next (iter, "{&sv}", &key, NULL))
    {
      info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &__hud_service_iface_com_canonical_hud_interface_info.parent_struct, key);
      g_datalist_remove_data (&proxy->priv->qdata, key);
      if (info != NULL)
        g_object_notify (G_OBJECT (proxy), info->hyphen_name);
    }
  g_variant_iter_free (iter);
  for (n = 0; invalidated_properties[n] != NULL; n++)
    {
      info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &__hud_service_iface_com_canonical_hud_interface_info.parent_struct, invalidated_properties[n]);
      g_datalist_remove_data (&proxy->priv->qdata, invalidated_properties[n]);
      if (info != NULL)
        g_object_notify (G_OBJECT (proxy), info->hyphen_name);
    }
}

static const gchar *const *
_hud_service_iface_com_canonical_hud_proxy_get_open_queries (_HudServiceIfaceComCanonicalHud *object)
{
  _HudServiceIfaceComCanonicalHudProxy *proxy = _HUD_SERVICE_IFACE_COM_CANONICAL_HUD_PROXY (object);
  GVariant *variant;
  const gchar *const *value = NULL;
  variant = g_dbus_proxy_get_cached_property (G_DBUS_PROXY (proxy), "OpenQueries");
  if (variant != NULL)
    {
      value = g_variant_get_objv (variant, NULL);
      g_variant_unref (variant);
    }
  return value;
}

static GVariant *
_hud_service_iface_com_canonical_hud_proxy_get_applications (_HudServiceIfaceComCanonicalHud *object)
{
  _HudServiceIfaceComCanonicalHudProxy *proxy = _HUD_SERVICE_IFACE_COM_CANONICAL_HUD_PROXY (object);
  GVariant *variant;
  GVariant *value = NULL;
  variant = g_dbus_proxy_get_cached_property (G_DBUS_PROXY (proxy), "Applications");
  value = variant;
  if (variant != NULL)
    g_variant_unref (variant);
  return value;
}

static void
_hud_service_iface_com_canonical_hud_proxy_init (_HudServiceIfaceComCanonicalHudProxy *proxy)
{
  proxy->priv = G_TYPE_INSTANCE_GET_PRIVATE (proxy, _HUD_SERVICE_IFACE_TYPE_COM_CANONICAL_HUD_PROXY, _HudServiceIfaceComCanonicalHudProxyPrivate);
  g_dbus_proxy_set_interface_info (G_DBUS_PROXY (proxy), _hud_service_iface_com_canonical_hud_interface_info ());
}

static void
_hud_service_iface_com_canonical_hud_proxy_class_init (_HudServiceIfaceComCanonicalHudProxyClass *klass)
{
  GObjectClass *gobject_class;
  GDBusProxyClass *proxy_class;

  g_type_class_add_private (klass, sizeof (_HudServiceIfaceComCanonicalHudProxyPrivate));

  gobject_class = G_OBJECT_CLASS (klass);
  gobject_class->finalize     = _hud_service_iface_com_canonical_hud_proxy_finalize;
  gobject_class->get_property = _hud_service_iface_com_canonical_hud_proxy_get_property;
  gobject_class->set_property = _hud_service_iface_com_canonical_hud_proxy_set_property;

  proxy_class = G_DBUS_PROXY_CLASS (klass);
  proxy_class->g_signal = _hud_service_iface_com_canonical_hud_proxy_g_signal;
  proxy_class->g_properties_changed = _hud_service_iface_com_canonical_hud_proxy_g_properties_changed;


  _hud_service_iface_com_canonical_hud_override_properties (gobject_class, 1);
}

static void
_hud_service_iface_com_canonical_hud_proxy_iface_init (_HudServiceIfaceComCanonicalHudIface *iface)
{
  iface->get_open_queries = _hud_service_iface_com_canonical_hud_proxy_get_open_queries;
  iface->get_applications = _hud_service_iface_com_canonical_hud_proxy_get_applications;
}

/**
 * _hud_service_iface_com_canonical_hud_proxy_new:
 * @connection: A #GDBusConnection.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: (allow-none): A bus name (well-known or unique) or %NULL if @connection is not a message bus connection.
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously creates a proxy for the D-Bus interface <link linkend="gdbus-interface-com-canonical-hud.top_of_page">com.canonical.hud</link>. See g_dbus_proxy_new() for more details.
 *
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call _hud_service_iface_com_canonical_hud_proxy_new_finish() to get the result of the operation.
 *
 * See _hud_service_iface_com_canonical_hud_proxy_new_sync() for the synchronous, blocking version of this constructor.
 */
void
_hud_service_iface_com_canonical_hud_proxy_new (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data)
{
  g_async_initable_new_async (_HUD_SERVICE_IFACE_TYPE_COM_CANONICAL_HUD_PROXY, G_PRIORITY_DEFAULT, cancellable, callback, user_data, "g-flags", flags, "g-name", name, "g-connection", connection, "g-object-path", object_path, "g-interface-name", "com.canonical.hud", NULL);
}

/**
 * _hud_service_iface_com_canonical_hud_proxy_new_finish:
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to _hud_service_iface_com_canonical_hud_proxy_new().
 * @error: Return location for error or %NULL
 *
 * Finishes an operation started with _hud_service_iface_com_canonical_hud_proxy_new().
 *
 * Returns: (transfer full) (type _HudServiceIfaceComCanonicalHudProxy): The constructed proxy object or %NULL if @error is set.
 */
_HudServiceIfaceComCanonicalHud *
_hud_service_iface_com_canonical_hud_proxy_new_finish (
    GAsyncResult        *res,
    GError             **error)
{
  GObject *ret;
  GObject *source_object;
  source_object = g_async_result_get_source_object (res);
  ret = g_async_initable_new_finish (G_ASYNC_INITABLE (source_object), res, error);
  g_object_unref (source_object);
  if (ret != NULL)
    return _HUD_SERVICE_IFACE_COM_CANONICAL_HUD (ret);
  else
    return NULL;
}

/**
 * _hud_service_iface_com_canonical_hud_proxy_new_sync:
 * @connection: A #GDBusConnection.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: (allow-none): A bus name (well-known or unique) or %NULL if @connection is not a message bus connection.
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL
 *
 * Synchronously creates a proxy for the D-Bus interface <link linkend="gdbus-interface-com-canonical-hud.top_of_page">com.canonical.hud</link>. See g_dbus_proxy_new_sync() for more details.
 *
 * The calling thread is blocked until a reply is received.
 *
 * See _hud_service_iface_com_canonical_hud_proxy_new() for the asynchronous version of this constructor.
 *
 * Returns: (transfer full) (type _HudServiceIfaceComCanonicalHudProxy): The constructed proxy object or %NULL if @error is set.
 */
_HudServiceIfaceComCanonicalHud *
_hud_service_iface_com_canonical_hud_proxy_new_sync (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error)
{
  GInitable *ret;
  ret = g_initable_new (_HUD_SERVICE_IFACE_TYPE_COM_CANONICAL_HUD_PROXY, cancellable, error, "g-flags", flags, "g-name", name, "g-connection", connection, "g-object-path", object_path, "g-interface-name", "com.canonical.hud", NULL);
  if (ret != NULL)
    return _HUD_SERVICE_IFACE_COM_CANONICAL_HUD (ret);
  else
    return NULL;
}


/**
 * _hud_service_iface_com_canonical_hud_proxy_new_for_bus:
 * @bus_type: A #GBusType.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: A bus name (well-known or unique).
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied.
 * @user_data: User data to pass to @callback.
 *
 * Like _hud_service_iface_com_canonical_hud_proxy_new() but takes a #GBusType instead of a #GDBusConnection.
 *
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call _hud_service_iface_com_canonical_hud_proxy_new_for_bus_finish() to get the result of the operation.
 *
 * See _hud_service_iface_com_canonical_hud_proxy_new_for_bus_sync() for the synchronous, blocking version of this constructor.
 */
void
_hud_service_iface_com_canonical_hud_proxy_new_for_bus (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data)
{
  g_async_initable_new_async (_HUD_SERVICE_IFACE_TYPE_COM_CANONICAL_HUD_PROXY, G_PRIORITY_DEFAULT, cancellable, callback, user_data, "g-flags", flags, "g-name", name, "g-bus-type", bus_type, "g-object-path", object_path, "g-interface-name", "com.canonical.hud", NULL);
}

/**
 * _hud_service_iface_com_canonical_hud_proxy_new_for_bus_finish:
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to _hud_service_iface_com_canonical_hud_proxy_new_for_bus().
 * @error: Return location for error or %NULL
 *
 * Finishes an operation started with _hud_service_iface_com_canonical_hud_proxy_new_for_bus().
 *
 * Returns: (transfer full) (type _HudServiceIfaceComCanonicalHudProxy): The constructed proxy object or %NULL if @error is set.
 */
_HudServiceIfaceComCanonicalHud *
_hud_service_iface_com_canonical_hud_proxy_new_for_bus_finish (
    GAsyncResult        *res,
    GError             **error)
{
  GObject *ret;
  GObject *source_object;
  source_object = g_async_result_get_source_object (res);
  ret = g_async_initable_new_finish (G_ASYNC_INITABLE (source_object), res, error);
  g_object_unref (source_object);
  if (ret != NULL)
    return _HUD_SERVICE_IFACE_COM_CANONICAL_HUD (ret);
  else
    return NULL;
}

/**
 * _hud_service_iface_com_canonical_hud_proxy_new_for_bus_sync:
 * @bus_type: A #GBusType.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: A bus name (well-known or unique).
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL
 *
 * Like _hud_service_iface_com_canonical_hud_proxy_new_sync() but takes a #GBusType instead of a #GDBusConnection.
 *
 * The calling thread is blocked until a reply is received.
 *
 * See _hud_service_iface_com_canonical_hud_proxy_new_for_bus() for the asynchronous version of this constructor.
 *
 * Returns: (transfer full) (type _HudServiceIfaceComCanonicalHudProxy): The constructed proxy object or %NULL if @error is set.
 */
_HudServiceIfaceComCanonicalHud *
_hud_service_iface_com_canonical_hud_proxy_new_for_bus_sync (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error)
{
  GInitable *ret;
  ret = g_initable_new (_HUD_SERVICE_IFACE_TYPE_COM_CANONICAL_HUD_PROXY, cancellable, error, "g-flags", flags, "g-name", name, "g-bus-type", bus_type, "g-object-path", object_path, "g-interface-name", "com.canonical.hud", NULL);
  if (ret != NULL)
    return _HUD_SERVICE_IFACE_COM_CANONICAL_HUD (ret);
  else
    return NULL;
}


/* ------------------------------------------------------------------------ */

/**
 * _HudServiceIfaceComCanonicalHudSkeleton:
 *
 * The #_HudServiceIfaceComCanonicalHudSkeleton structure contains only private data and should only be accessed using the provided API.
 */

/**
 * _HudServiceIfaceComCanonicalHudSkeletonClass:
 * @parent_class: The parent class.
 *
 * Class structure for #_HudServiceIfaceComCanonicalHudSkeleton.
 */

struct __HudServiceIfaceComCanonicalHudSkeletonPrivate
{
  GValue *properties;
  GList *changed_properties;
  GSource *changed_properties_idle_source;
  GMainContext *context;
  GMutex lock;
};

static void
__hud_service_iface_com_canonical_hud_skeleton_handle_method_call (
  GDBusConnection *connection,
  const gchar *sender,
  const gchar *object_path,
  const gchar *interface_name,
  const gchar *method_name,
  GVariant *parameters,
  GDBusMethodInvocation *invocation,
  gpointer user_data)
{
  _HudServiceIfaceComCanonicalHudSkeleton *skeleton = _HUD_SERVICE_IFACE_COM_CANONICAL_HUD_SKELETON (user_data);
  _ExtendedGDBusMethodInfo *info;
  GVariantIter iter;
  GVariant *child;
  GValue *paramv;
  guint num_params;
  guint num_extra;
  guint n;
  guint signal_id;
  GValue return_value = G_VALUE_INIT;
  info = (_ExtendedGDBusMethodInfo *) g_dbus_method_invocation_get_method_info (invocation);
  g_assert (info != NULL);
  num_params = g_variant_n_children (parameters);
  num_extra = info->pass_fdlist ? 3 : 2;  paramv = g_new0 (GValue, num_params + num_extra);
  n = 0;
  g_value_init (&paramv[n], _HUD_SERVICE_IFACE_TYPE_COM_CANONICAL_HUD);
  g_value_set_object (&paramv[n++], skeleton);
  g_value_init (&paramv[n], G_TYPE_DBUS_METHOD_INVOCATION);
  g_value_set_object (&paramv[n++], invocation);
  if (info->pass_fdlist)
    {
#ifdef G_OS_UNIX
      g_value_init (&paramv[n], G_TYPE_UNIX_FD_LIST);
      g_value_set_object (&paramv[n++], g_dbus_message_get_unix_fd_list (g_dbus_method_invocation_get_message (invocation)));
#else
      g_assert_not_reached ();
#endif
    }
  g_variant_iter_init (&iter, parameters);
  while ((child = g_variant_iter_next_value (&iter)) != NULL)
    {
      _ExtendedGDBusArgInfo *arg_info = (_ExtendedGDBusArgInfo *) info->parent_struct.in_args[n - num_extra];
      if (arg_info->use_gvariant)
        {
          g_value_init (&paramv[n], G_TYPE_VARIANT);
          g_value_set_variant (&paramv[n], child);
          n++;
        }
      else
        g_dbus_gvariant_to_gvalue (child, &paramv[n++]);
      g_variant_unref (child);
    }
  signal_id = g_signal_lookup (info->signal_name, _HUD_SERVICE_IFACE_TYPE_COM_CANONICAL_HUD);
  g_value_init (&return_value, G_TYPE_BOOLEAN);
  g_signal_emitv (paramv, signal_id, 0, &return_value);
  if (!g_value_get_boolean (&return_value))
    g_dbus_method_invocation_return_error (invocation, G_DBUS_ERROR, G_DBUS_ERROR_UNKNOWN_METHOD, "Method %s is not implemented on interface %s", method_name, interface_name);
  g_value_unset (&return_value);
  for (n = 0; n < num_params + num_extra; n++)
    g_value_unset (&paramv[n]);
  g_free (paramv);
}

static GVariant *
__hud_service_iface_com_canonical_hud_skeleton_handle_get_property (
  GDBusConnection *connection,
  const gchar *sender,
  const gchar *object_path,
  const gchar *interface_name,
  const gchar *property_name,
  GError **error,
  gpointer user_data)
{
  _HudServiceIfaceComCanonicalHudSkeleton *skeleton = _HUD_SERVICE_IFACE_COM_CANONICAL_HUD_SKELETON (user_data);
  GValue value = G_VALUE_INIT;
  GParamSpec *pspec;
  _ExtendedGDBusPropertyInfo *info;
  GVariant *ret;
  ret = NULL;
  info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &__hud_service_iface_com_canonical_hud_interface_info.parent_struct, property_name);
  g_assert (info != NULL);
  pspec = g_object_class_find_property (G_OBJECT_GET_CLASS (skeleton), info->hyphen_name);
  if (pspec == NULL)
    {
      g_set_error (error, G_DBUS_ERROR, G_DBUS_ERROR_INVALID_ARGS, "No property with name %s", property_name);
    }
  else
    {
      g_value_init (&value, pspec->value_type);
      g_object_get_property (G_OBJECT (skeleton), info->hyphen_name, &value);
      ret = g_dbus_gvalue_to_gvariant (&value, G_VARIANT_TYPE (info->parent_struct.signature));
      g_value_unset (&value);
    }
  return ret;
}

static gboolean
__hud_service_iface_com_canonical_hud_skeleton_handle_set_property (
  GDBusConnection *connection,
  const gchar *sender,
  const gchar *object_path,
  const gchar *interface_name,
  const gchar *property_name,
  GVariant *variant,
  GError **error,
  gpointer user_data)
{
  _HudServiceIfaceComCanonicalHudSkeleton *skeleton = _HUD_SERVICE_IFACE_COM_CANONICAL_HUD_SKELETON (user_data);
  GValue value = G_VALUE_INIT;
  GParamSpec *pspec;
  _ExtendedGDBusPropertyInfo *info;
  gboolean ret;
  ret = FALSE;
  info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &__hud_service_iface_com_canonical_hud_interface_info.parent_struct, property_name);
  g_assert (info != NULL);
  pspec = g_object_class_find_property (G_OBJECT_GET_CLASS (skeleton), info->hyphen_name);
  if (pspec == NULL)
    {
      g_set_error (error, G_DBUS_ERROR, G_DBUS_ERROR_INVALID_ARGS, "No property with name %s", property_name);
    }
  else
    {
      if (info->use_gvariant)
        g_value_set_variant (&value, variant);
      else
        g_dbus_gvariant_to_gvalue (variant, &value);
      g_object_set_property (G_OBJECT (skeleton), info->hyphen_name, &value);
      g_value_unset (&value);
      ret = TRUE;
    }
  return ret;
}

static const GDBusInterfaceVTable __hud_service_iface_com_canonical_hud_skeleton_vtable =
{
  __hud_service_iface_com_canonical_hud_skeleton_handle_method_call,
  __hud_service_iface_com_canonical_hud_skeleton_handle_get_property,
  __hud_service_iface_com_canonical_hud_skeleton_handle_set_property
};

static GDBusInterfaceInfo *
_hud_service_iface_com_canonical_hud_skeleton_dbus_interface_get_info (GDBusInterfaceSkeleton *skeleton)
{
  return _hud_service_iface_com_canonical_hud_interface_info ();
}

static GDBusInterfaceVTable *
_hud_service_iface_com_canonical_hud_skeleton_dbus_interface_get_vtable (GDBusInterfaceSkeleton *skeleton)
{
  return (GDBusInterfaceVTable *) &__hud_service_iface_com_canonical_hud_skeleton_vtable;
}

static GVariant *
_hud_service_iface_com_canonical_hud_skeleton_dbus_interface_get_properties (GDBusInterfaceSkeleton *_skeleton)
{
  _HudServiceIfaceComCanonicalHudSkeleton *skeleton = _HUD_SERVICE_IFACE_COM_CANONICAL_HUD_SKELETON (_skeleton);

  GVariantBuilder builder;
  guint n;
  g_variant_builder_init (&builder, G_VARIANT_TYPE ("a{sv}"));
  if (__hud_service_iface_com_canonical_hud_interface_info.parent_struct.properties == NULL)
    goto out;
  for (n = 0; __hud_service_iface_com_canonical_hud_interface_info.parent_struct.properties[n] != NULL; n++)
    {
      GDBusPropertyInfo *info = __hud_service_iface_com_canonical_hud_interface_info.parent_struct.properties[n];
      if (info->flags & G_DBUS_PROPERTY_INFO_FLAGS_READABLE)
        {
          GVariant *value;
          value = __hud_service_iface_com_canonical_hud_skeleton_handle_get_property (g_dbus_interface_skeleton_get_connection (G_DBUS_INTERFACE_SKELETON (skeleton)), NULL, g_dbus_interface_skeleton_get_object_path (G_DBUS_INTERFACE_SKELETON (skeleton)), "com.canonical.hud", info->name, NULL, skeleton);
          if (value != NULL)
            {
              g_variant_take_ref (value);
              g_variant_builder_add (&builder, "{sv}", info->name, value);
              g_variant_unref (value);
            }
        }
    }
out:
  return g_variant_builder_end (&builder);
}

static gboolean __hud_service_iface_com_canonical_hud_emit_changed (gpointer user_data);

static void
_hud_service_iface_com_canonical_hud_skeleton_dbus_interface_flush (GDBusInterfaceSkeleton *_skeleton)
{
  _HudServiceIfaceComCanonicalHudSkeleton *skeleton = _HUD_SERVICE_IFACE_COM_CANONICAL_HUD_SKELETON (_skeleton);
  gboolean emit_changed = FALSE;

  g_mutex_lock (&skeleton->priv->lock);
  if (skeleton->priv->changed_properties_idle_source != NULL)
    {
      g_source_destroy (skeleton->priv->changed_properties_idle_source);
      skeleton->priv->changed_properties_idle_source = NULL;
      emit_changed = TRUE;
    }
  g_mutex_unlock (&skeleton->priv->lock);

  if (emit_changed)
    __hud_service_iface_com_canonical_hud_emit_changed (skeleton);
}

static void _hud_service_iface_com_canonical_hud_skeleton_iface_init (_HudServiceIfaceComCanonicalHudIface *iface);
G_DEFINE_TYPE_WITH_CODE (_HudServiceIfaceComCanonicalHudSkeleton, _hud_service_iface_com_canonical_hud_skeleton, G_TYPE_DBUS_INTERFACE_SKELETON,
                         G_IMPLEMENT_INTERFACE (_HUD_SERVICE_IFACE_TYPE_COM_CANONICAL_HUD, _hud_service_iface_com_canonical_hud_skeleton_iface_init));

static void
_hud_service_iface_com_canonical_hud_skeleton_finalize (GObject *object)
{
  _HudServiceIfaceComCanonicalHudSkeleton *skeleton = _HUD_SERVICE_IFACE_COM_CANONICAL_HUD_SKELETON (object);
  guint n;
  for (n = 0; n < 2; n++)
    g_value_unset (&skeleton->priv->properties[n]);
  g_free (skeleton->priv->properties);
  g_list_free_full (skeleton->priv->changed_properties, (GDestroyNotify) _changed_property_free);
  if (skeleton->priv->changed_properties_idle_source != NULL)
    g_source_destroy (skeleton->priv->changed_properties_idle_source);
  g_main_context_unref (skeleton->priv->context);
  g_mutex_clear (&skeleton->priv->lock);
  G_OBJECT_CLASS (_hud_service_iface_com_canonical_hud_skeleton_parent_class)->finalize (object);
}

static void
_hud_service_iface_com_canonical_hud_skeleton_get_property (GObject      *object,
  guint         prop_id,
  GValue       *value,
  GParamSpec   *pspec)
{
  _HudServiceIfaceComCanonicalHudSkeleton *skeleton = _HUD_SERVICE_IFACE_COM_CANONICAL_HUD_SKELETON (object);
  g_assert (prop_id != 0 && prop_id - 1 < 2);
  g_mutex_lock (&skeleton->priv->lock);
  g_value_copy (&skeleton->priv->properties[prop_id - 1], value);
  g_mutex_unlock (&skeleton->priv->lock);
}

static gboolean
__hud_service_iface_com_canonical_hud_emit_changed (gpointer user_data)
{
  _HudServiceIfaceComCanonicalHudSkeleton *skeleton = _HUD_SERVICE_IFACE_COM_CANONICAL_HUD_SKELETON (user_data);
  GList *l;
  GVariantBuilder builder;
  GVariantBuilder invalidated_builder;
  guint num_changes;

  g_mutex_lock (&skeleton->priv->lock);
  g_variant_builder_init (&builder, G_VARIANT_TYPE ("a{sv}"));
  g_variant_builder_init (&invalidated_builder, G_VARIANT_TYPE ("as"));
  for (l = skeleton->priv->changed_properties, num_changes = 0; l != NULL; l = l->next)
    {
      ChangedProperty *cp = l->data;
      GVariant *variant;
      const GValue *cur_value;

      cur_value = &skeleton->priv->properties[cp->prop_id - 1];
      if (!_g_value_equal (cur_value, &cp->orig_value))
        {
          variant = g_dbus_gvalue_to_gvariant (cur_value, G_VARIANT_TYPE (cp->info->parent_struct.signature));
          g_variant_builder_add (&builder, "{sv}", cp->info->parent_struct.name, variant);
          g_variant_unref (variant);
          num_changes++;
        }
    }
  if (num_changes > 0)
    {
      GList *connections, *ll;
      GVariant *signal_variant;
      signal_variant = g_variant_ref_sink (g_variant_new ("(sa{sv}as)", "com.canonical.hud",
                                           &builder, &invalidated_builder));
      connections = g_dbus_interface_skeleton_get_connections (G_DBUS_INTERFACE_SKELETON (skeleton));
      for (ll = connections; ll != NULL; ll = ll->next)
        {
          GDBusConnection *connection = ll->data;

          g_dbus_connection_emit_signal (connection,
                                         NULL, g_dbus_interface_skeleton_get_object_path (G_DBUS_INTERFACE_SKELETON (skeleton)),
                                         "org.freedesktop.DBus.Properties",
                                         "PropertiesChanged",
                                         signal_variant,
                                         NULL);
        }
      g_variant_unref (signal_variant);
      g_list_free_full (connections, g_object_unref);
    }
  else
    {
      g_variant_builder_clear (&builder);
      g_variant_builder_clear (&invalidated_builder);
    }
  g_list_free_full (skeleton->priv->changed_properties, (GDestroyNotify) _changed_property_free);
  skeleton->priv->changed_properties = NULL;
  skeleton->priv->changed_properties_idle_source = NULL;
  g_mutex_unlock (&skeleton->priv->lock);
  return FALSE;
}

static void
__hud_service_iface_com_canonical_hud_schedule_emit_changed (_HudServiceIfaceComCanonicalHudSkeleton *skeleton, const _ExtendedGDBusPropertyInfo *info, guint prop_id, const GValue *orig_value)
{
  ChangedProperty *cp;
  GList *l;
  cp = NULL;
  for (l = skeleton->priv->changed_properties; l != NULL; l = l->next)
    {
      ChangedProperty *i_cp = l->data;
      if (i_cp->info == info)
        {
          cp = i_cp;
          break;
        }
    }
  if (cp == NULL)
    {
      cp = g_new0 (ChangedProperty, 1);
      cp->prop_id = prop_id;
      cp->info = info;
      skeleton->priv->changed_properties = g_list_prepend (skeleton->priv->changed_properties, cp);
      g_value_init (&cp->orig_value, G_VALUE_TYPE (orig_value));
      g_value_copy (orig_value, &cp->orig_value);
    }
}

static void
_hud_service_iface_com_canonical_hud_skeleton_notify (GObject      *object,
  GParamSpec *pspec)
{
  _HudServiceIfaceComCanonicalHudSkeleton *skeleton = _HUD_SERVICE_IFACE_COM_CANONICAL_HUD_SKELETON (object);
  g_mutex_lock (&skeleton->priv->lock);
  if (skeleton->priv->changed_properties != NULL &&
      skeleton->priv->changed_properties_idle_source == NULL)
    {
      skeleton->priv->changed_properties_idle_source = g_idle_source_new ();
      g_source_set_priority (skeleton->priv->changed_properties_idle_source, G_PRIORITY_DEFAULT);
      g_source_set_callback (skeleton->priv->changed_properties_idle_source, __hud_service_iface_com_canonical_hud_emit_changed, g_object_ref (skeleton), (GDestroyNotify) g_object_unref);
      g_source_attach (skeleton->priv->changed_properties_idle_source, skeleton->priv->context);
      g_source_unref (skeleton->priv->changed_properties_idle_source);
    }
  g_mutex_unlock (&skeleton->priv->lock);
}

static void
_hud_service_iface_com_canonical_hud_skeleton_set_property (GObject      *object,
  guint         prop_id,
  const GValue *value,
  GParamSpec   *pspec)
{
  _HudServiceIfaceComCanonicalHudSkeleton *skeleton = _HUD_SERVICE_IFACE_COM_CANONICAL_HUD_SKELETON (object);
  g_assert (prop_id != 0 && prop_id - 1 < 2);
  g_mutex_lock (&skeleton->priv->lock);
  g_object_freeze_notify (object);
  if (!_g_value_equal (value, &skeleton->priv->properties[prop_id - 1]))
    {
      if (g_dbus_interface_skeleton_get_connection (G_DBUS_INTERFACE_SKELETON (skeleton)) != NULL)
        __hud_service_iface_com_canonical_hud_schedule_emit_changed (skeleton, __hud_service_iface_com_canonical_hud_property_info_pointers[prop_id - 1], prop_id, &skeleton->priv->properties[prop_id - 1]);
      g_value_copy (value, &skeleton->priv->properties[prop_id - 1]);
      g_object_notify_by_pspec (object, pspec);
    }
  g_mutex_unlock (&skeleton->priv->lock);
  g_object_thaw_notify (object);
}

static void
_hud_service_iface_com_canonical_hud_skeleton_init (_HudServiceIfaceComCanonicalHudSkeleton *skeleton)
{
  skeleton->priv = G_TYPE_INSTANCE_GET_PRIVATE (skeleton, _HUD_SERVICE_IFACE_TYPE_COM_CANONICAL_HUD_SKELETON, _HudServiceIfaceComCanonicalHudSkeletonPrivate);
  g_mutex_init (&skeleton->priv->lock);
  skeleton->priv->context = g_main_context_ref_thread_default ();
  skeleton->priv->properties = g_new0 (GValue, 2);
  g_value_init (&skeleton->priv->properties[0], G_TYPE_STRV);
  g_value_init (&skeleton->priv->properties[1], G_TYPE_VARIANT);
}

static const gchar *const *
_hud_service_iface_com_canonical_hud_skeleton_get_open_queries (_HudServiceIfaceComCanonicalHud *object)
{
  _HudServiceIfaceComCanonicalHudSkeleton *skeleton = _HUD_SERVICE_IFACE_COM_CANONICAL_HUD_SKELETON (object);
  const gchar *const *value;
  g_mutex_lock (&skeleton->priv->lock);
  value = g_value_get_boxed (&(skeleton->priv->properties[0]));
  g_mutex_unlock (&skeleton->priv->lock);
  return value;
}

static GVariant *
_hud_service_iface_com_canonical_hud_skeleton_get_applications (_HudServiceIfaceComCanonicalHud *object)
{
  _HudServiceIfaceComCanonicalHudSkeleton *skeleton = _HUD_SERVICE_IFACE_COM_CANONICAL_HUD_SKELETON (object);
  GVariant *value;
  g_mutex_lock (&skeleton->priv->lock);
  value = g_value_get_variant (&(skeleton->priv->properties[1]));
  g_mutex_unlock (&skeleton->priv->lock);
  return value;
}

static void
_hud_service_iface_com_canonical_hud_skeleton_class_init (_HudServiceIfaceComCanonicalHudSkeletonClass *klass)
{
  GObjectClass *gobject_class;
  GDBusInterfaceSkeletonClass *skeleton_class;

  g_type_class_add_private (klass, sizeof (_HudServiceIfaceComCanonicalHudSkeletonPrivate));

  gobject_class = G_OBJECT_CLASS (klass);
  gobject_class->finalize = _hud_service_iface_com_canonical_hud_skeleton_finalize;
  gobject_class->get_property = _hud_service_iface_com_canonical_hud_skeleton_get_property;
  gobject_class->set_property = _hud_service_iface_com_canonical_hud_skeleton_set_property;
  gobject_class->notify       = _hud_service_iface_com_canonical_hud_skeleton_notify;


  _hud_service_iface_com_canonical_hud_override_properties (gobject_class, 1);

  skeleton_class = G_DBUS_INTERFACE_SKELETON_CLASS (klass);
  skeleton_class->get_info = _hud_service_iface_com_canonical_hud_skeleton_dbus_interface_get_info;
  skeleton_class->get_properties = _hud_service_iface_com_canonical_hud_skeleton_dbus_interface_get_properties;
  skeleton_class->flush = _hud_service_iface_com_canonical_hud_skeleton_dbus_interface_flush;
  skeleton_class->get_vtable = _hud_service_iface_com_canonical_hud_skeleton_dbus_interface_get_vtable;
}

static void
_hud_service_iface_com_canonical_hud_skeleton_iface_init (_HudServiceIfaceComCanonicalHudIface *iface)
{
  iface->get_open_queries = _hud_service_iface_com_canonical_hud_skeleton_get_open_queries;
  iface->get_applications = _hud_service_iface_com_canonical_hud_skeleton_get_applications;
}

/**
 * _hud_service_iface_com_canonical_hud_skeleton_new:
 *
 * Creates a skeleton object for the D-Bus interface <link linkend="gdbus-interface-com-canonical-hud.top_of_page">com.canonical.hud</link>.
 *
 * Returns: (transfer full) (type _HudServiceIfaceComCanonicalHudSkeleton): The skeleton object.
 */
_HudServiceIfaceComCanonicalHud *
_hud_service_iface_com_canonical_hud_skeleton_new (void)
{
  return _HUD_SERVICE_IFACE_COM_CANONICAL_HUD (g_object_new (_HUD_SERVICE_IFACE_TYPE_COM_CANONICAL_HUD_SKELETON, NULL));
}

