/*
 * Generated by gdbus-codegen 2.34.1. DO NOT EDIT.
 *
 * The license of this code is the same as for the source it was derived from.
 */

#ifndef __APP_IFACE_H__
#define __APP_IFACE_H__

#include <gio/gio.h>

G_BEGIN_DECLS


/* ------------------------------------------------------------------------ */
/* Declarations for com.canonical.hud.Application */

#define APP_IFACE_TYPE_COM_CANONICAL_HUD_APPLICATION (app_iface_com_canonical_hud_application_get_type ())
#define APP_IFACE_COM_CANONICAL_HUD_APPLICATION(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), APP_IFACE_TYPE_COM_CANONICAL_HUD_APPLICATION, AppIfaceComCanonicalHudApplication))
#define APP_IFACE_IS_COM_CANONICAL_HUD_APPLICATION(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), APP_IFACE_TYPE_COM_CANONICAL_HUD_APPLICATION))
#define APP_IFACE_COM_CANONICAL_HUD_APPLICATION_GET_IFACE(o) (G_TYPE_INSTANCE_GET_INTERFACE ((o), APP_IFACE_TYPE_COM_CANONICAL_HUD_APPLICATION, AppIfaceComCanonicalHudApplicationIface))

struct _AppIfaceComCanonicalHudApplication;
typedef struct _AppIfaceComCanonicalHudApplication AppIfaceComCanonicalHudApplication;
typedef struct _AppIfaceComCanonicalHudApplicationIface AppIfaceComCanonicalHudApplicationIface;

struct _AppIfaceComCanonicalHudApplicationIface
{
  GTypeInterface parent_iface;


  gboolean (*handle_add_sources) (
    AppIfaceComCanonicalHudApplication *object,
    GDBusMethodInvocation *invocation,
    GVariant *arg_actions,
    GVariant *arg_descriptions);

  GVariant * (*get_action_groups) (AppIfaceComCanonicalHudApplication *object);

  const gchar * (*get_desktop_path) (AppIfaceComCanonicalHudApplication *object);

  const gchar * (*get_icon) (AppIfaceComCanonicalHudApplication *object);

  GVariant * (*get_menu_models) (AppIfaceComCanonicalHudApplication *object);

};

GType app_iface_com_canonical_hud_application_get_type (void) G_GNUC_CONST;

GDBusInterfaceInfo *app_iface_com_canonical_hud_application_interface_info (void);
guint app_iface_com_canonical_hud_application_override_properties (GObjectClass *klass, guint property_id_begin);


/* D-Bus method call completion functions: */
void app_iface_com_canonical_hud_application_complete_add_sources (
    AppIfaceComCanonicalHudApplication *object,
    GDBusMethodInvocation *invocation);



/* D-Bus method calls: */
void app_iface_com_canonical_hud_application_call_add_sources (
    AppIfaceComCanonicalHudApplication *proxy,
    GVariant *arg_actions,
    GVariant *arg_descriptions,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean app_iface_com_canonical_hud_application_call_add_sources_finish (
    AppIfaceComCanonicalHudApplication *proxy,
    GAsyncResult *res,
    GError **error);

gboolean app_iface_com_canonical_hud_application_call_add_sources_sync (
    AppIfaceComCanonicalHudApplication *proxy,
    GVariant *arg_actions,
    GVariant *arg_descriptions,
    GCancellable *cancellable,
    GError **error);



/* D-Bus property accessors: */
GVariant *app_iface_com_canonical_hud_application_get_action_groups (AppIfaceComCanonicalHudApplication *object);
GVariant *app_iface_com_canonical_hud_application_dup_action_groups (AppIfaceComCanonicalHudApplication *object);
void app_iface_com_canonical_hud_application_set_action_groups (AppIfaceComCanonicalHudApplication *object, GVariant *value);

GVariant *app_iface_com_canonical_hud_application_get_menu_models (AppIfaceComCanonicalHudApplication *object);
GVariant *app_iface_com_canonical_hud_application_dup_menu_models (AppIfaceComCanonicalHudApplication *object);
void app_iface_com_canonical_hud_application_set_menu_models (AppIfaceComCanonicalHudApplication *object, GVariant *value);

const gchar *app_iface_com_canonical_hud_application_get_desktop_path (AppIfaceComCanonicalHudApplication *object);
gchar *app_iface_com_canonical_hud_application_dup_desktop_path (AppIfaceComCanonicalHudApplication *object);
void app_iface_com_canonical_hud_application_set_desktop_path (AppIfaceComCanonicalHudApplication *object, const gchar *value);

const gchar *app_iface_com_canonical_hud_application_get_icon (AppIfaceComCanonicalHudApplication *object);
gchar *app_iface_com_canonical_hud_application_dup_icon (AppIfaceComCanonicalHudApplication *object);
void app_iface_com_canonical_hud_application_set_icon (AppIfaceComCanonicalHudApplication *object, const gchar *value);


/* ---- */

#define APP_IFACE_TYPE_COM_CANONICAL_HUD_APPLICATION_PROXY (app_iface_com_canonical_hud_application_proxy_get_type ())
#define APP_IFACE_COM_CANONICAL_HUD_APPLICATION_PROXY(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), APP_IFACE_TYPE_COM_CANONICAL_HUD_APPLICATION_PROXY, AppIfaceComCanonicalHudApplicationProxy))
#define APP_IFACE_COM_CANONICAL_HUD_APPLICATION_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), APP_IFACE_TYPE_COM_CANONICAL_HUD_APPLICATION_PROXY, AppIfaceComCanonicalHudApplicationProxyClass))
#define APP_IFACE_COM_CANONICAL_HUD_APPLICATION_PROXY_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), APP_IFACE_TYPE_COM_CANONICAL_HUD_APPLICATION_PROXY, AppIfaceComCanonicalHudApplicationProxyClass))
#define APP_IFACE_IS_COM_CANONICAL_HUD_APPLICATION_PROXY(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), APP_IFACE_TYPE_COM_CANONICAL_HUD_APPLICATION_PROXY))
#define APP_IFACE_IS_COM_CANONICAL_HUD_APPLICATION_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), APP_IFACE_TYPE_COM_CANONICAL_HUD_APPLICATION_PROXY))

typedef struct _AppIfaceComCanonicalHudApplicationProxy AppIfaceComCanonicalHudApplicationProxy;
typedef struct _AppIfaceComCanonicalHudApplicationProxyClass AppIfaceComCanonicalHudApplicationProxyClass;
typedef struct _AppIfaceComCanonicalHudApplicationProxyPrivate AppIfaceComCanonicalHudApplicationProxyPrivate;

struct _AppIfaceComCanonicalHudApplicationProxy
{
  /*< private >*/
  GDBusProxy parent_instance;
  AppIfaceComCanonicalHudApplicationProxyPrivate *priv;
};

struct _AppIfaceComCanonicalHudApplicationProxyClass
{
  GDBusProxyClass parent_class;
};

GType app_iface_com_canonical_hud_application_proxy_get_type (void) G_GNUC_CONST;

void app_iface_com_canonical_hud_application_proxy_new (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data);
AppIfaceComCanonicalHudApplication *app_iface_com_canonical_hud_application_proxy_new_finish (
    GAsyncResult        *res,
    GError             **error);
AppIfaceComCanonicalHudApplication *app_iface_com_canonical_hud_application_proxy_new_sync (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error);

void app_iface_com_canonical_hud_application_proxy_new_for_bus (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data);
AppIfaceComCanonicalHudApplication *app_iface_com_canonical_hud_application_proxy_new_for_bus_finish (
    GAsyncResult        *res,
    GError             **error);
AppIfaceComCanonicalHudApplication *app_iface_com_canonical_hud_application_proxy_new_for_bus_sync (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error);


/* ---- */

#define APP_IFACE_TYPE_COM_CANONICAL_HUD_APPLICATION_SKELETON (app_iface_com_canonical_hud_application_skeleton_get_type ())
#define APP_IFACE_COM_CANONICAL_HUD_APPLICATION_SKELETON(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), APP_IFACE_TYPE_COM_CANONICAL_HUD_APPLICATION_SKELETON, AppIfaceComCanonicalHudApplicationSkeleton))
#define APP_IFACE_COM_CANONICAL_HUD_APPLICATION_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), APP_IFACE_TYPE_COM_CANONICAL_HUD_APPLICATION_SKELETON, AppIfaceComCanonicalHudApplicationSkeletonClass))
#define APP_IFACE_COM_CANONICAL_HUD_APPLICATION_SKELETON_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), APP_IFACE_TYPE_COM_CANONICAL_HUD_APPLICATION_SKELETON, AppIfaceComCanonicalHudApplicationSkeletonClass))
#define APP_IFACE_IS_COM_CANONICAL_HUD_APPLICATION_SKELETON(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), APP_IFACE_TYPE_COM_CANONICAL_HUD_APPLICATION_SKELETON))
#define APP_IFACE_IS_COM_CANONICAL_HUD_APPLICATION_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), APP_IFACE_TYPE_COM_CANONICAL_HUD_APPLICATION_SKELETON))

typedef struct _AppIfaceComCanonicalHudApplicationSkeleton AppIfaceComCanonicalHudApplicationSkeleton;
typedef struct _AppIfaceComCanonicalHudApplicationSkeletonClass AppIfaceComCanonicalHudApplicationSkeletonClass;
typedef struct _AppIfaceComCanonicalHudApplicationSkeletonPrivate AppIfaceComCanonicalHudApplicationSkeletonPrivate;

struct _AppIfaceComCanonicalHudApplicationSkeleton
{
  /*< private >*/
  GDBusInterfaceSkeleton parent_instance;
  AppIfaceComCanonicalHudApplicationSkeletonPrivate *priv;
};

struct _AppIfaceComCanonicalHudApplicationSkeletonClass
{
  GDBusInterfaceSkeletonClass parent_class;
};

GType app_iface_com_canonical_hud_application_skeleton_get_type (void) G_GNUC_CONST;

AppIfaceComCanonicalHudApplication *app_iface_com_canonical_hud_application_skeleton_new (void);


G_END_DECLS

#endif /* __APP_IFACE_H__ */
