/*
 * Generated by gdbus-codegen 2.34.1. DO NOT EDIT.
 *
 * The license of this code is the same as for the source it was derived from.
 */

#ifndef __HUD_IFACE_H__
#define __HUD_IFACE_H__

#include <gio/gio.h>

G_BEGIN_DECLS


/* ------------------------------------------------------------------------ */
/* Declarations for com.canonical.hud */

#define HUD_IFACE_TYPE_COM_CANONICAL_HUD (hud_iface_com_canonical_hud_get_type ())
#define HUD_IFACE_COM_CANONICAL_HUD(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), HUD_IFACE_TYPE_COM_CANONICAL_HUD, HudIfaceComCanonicalHud))
#define HUD_IFACE_IS_COM_CANONICAL_HUD(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), HUD_IFACE_TYPE_COM_CANONICAL_HUD))
#define HUD_IFACE_COM_CANONICAL_HUD_GET_IFACE(o) (G_TYPE_INSTANCE_GET_INTERFACE ((o), HUD_IFACE_TYPE_COM_CANONICAL_HUD, HudIfaceComCanonicalHudIface))

struct _HudIfaceComCanonicalHud;
typedef struct _HudIfaceComCanonicalHud HudIfaceComCanonicalHud;
typedef struct _HudIfaceComCanonicalHudIface HudIfaceComCanonicalHudIface;

struct _HudIfaceComCanonicalHudIface
{
  GTypeInterface parent_iface;


  gboolean (*handle_register_application) (
    HudIfaceComCanonicalHud *object,
    GDBusMethodInvocation *invocation,
    const gchar *arg_id);

  gboolean (*handle_start_query) (
    HudIfaceComCanonicalHud *object,
    GDBusMethodInvocation *invocation,
    const gchar *arg_query);

  GVariant * (*get_applications) (HudIfaceComCanonicalHud *object);

  const gchar *const * (*get_open_queries) (HudIfaceComCanonicalHud *object);

};

GType hud_iface_com_canonical_hud_get_type (void) G_GNUC_CONST;

GDBusInterfaceInfo *hud_iface_com_canonical_hud_interface_info (void);
guint hud_iface_com_canonical_hud_override_properties (GObjectClass *klass, guint property_id_begin);


/* D-Bus method call completion functions: */
void hud_iface_com_canonical_hud_complete_start_query (
    HudIfaceComCanonicalHud *object,
    GDBusMethodInvocation *invocation,
    const gchar *queryObject,
    const gchar *resultsName,
    const gchar *appstackName,
    gint modelRevision);

void hud_iface_com_canonical_hud_complete_register_application (
    HudIfaceComCanonicalHud *object,
    GDBusMethodInvocation *invocation,
    const gchar *appObject);



/* D-Bus method calls: */
void hud_iface_com_canonical_hud_call_start_query (
    HudIfaceComCanonicalHud *proxy,
    const gchar *arg_query,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean hud_iface_com_canonical_hud_call_start_query_finish (
    HudIfaceComCanonicalHud *proxy,
    gchar **out_queryObject,
    gchar **out_resultsName,
    gchar **out_appstackName,
    gint *out_modelRevision,
    GAsyncResult *res,
    GError **error);

gboolean hud_iface_com_canonical_hud_call_start_query_sync (
    HudIfaceComCanonicalHud *proxy,
    const gchar *arg_query,
    gchar **out_queryObject,
    gchar **out_resultsName,
    gchar **out_appstackName,
    gint *out_modelRevision,
    GCancellable *cancellable,
    GError **error);

void hud_iface_com_canonical_hud_call_register_application (
    HudIfaceComCanonicalHud *proxy,
    const gchar *arg_id,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean hud_iface_com_canonical_hud_call_register_application_finish (
    HudIfaceComCanonicalHud *proxy,
    gchar **out_appObject,
    GAsyncResult *res,
    GError **error);

gboolean hud_iface_com_canonical_hud_call_register_application_sync (
    HudIfaceComCanonicalHud *proxy,
    const gchar *arg_id,
    gchar **out_appObject,
    GCancellable *cancellable,
    GError **error);



/* D-Bus property accessors: */
const gchar *const *hud_iface_com_canonical_hud_get_open_queries (HudIfaceComCanonicalHud *object);
gchar **hud_iface_com_canonical_hud_dup_open_queries (HudIfaceComCanonicalHud *object);
void hud_iface_com_canonical_hud_set_open_queries (HudIfaceComCanonicalHud *object, const gchar *const *value);

GVariant *hud_iface_com_canonical_hud_get_applications (HudIfaceComCanonicalHud *object);
GVariant *hud_iface_com_canonical_hud_dup_applications (HudIfaceComCanonicalHud *object);
void hud_iface_com_canonical_hud_set_applications (HudIfaceComCanonicalHud *object, GVariant *value);


/* ---- */

#define HUD_IFACE_TYPE_COM_CANONICAL_HUD_PROXY (hud_iface_com_canonical_hud_proxy_get_type ())
#define HUD_IFACE_COM_CANONICAL_HUD_PROXY(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), HUD_IFACE_TYPE_COM_CANONICAL_HUD_PROXY, HudIfaceComCanonicalHudProxy))
#define HUD_IFACE_COM_CANONICAL_HUD_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), HUD_IFACE_TYPE_COM_CANONICAL_HUD_PROXY, HudIfaceComCanonicalHudProxyClass))
#define HUD_IFACE_COM_CANONICAL_HUD_PROXY_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), HUD_IFACE_TYPE_COM_CANONICAL_HUD_PROXY, HudIfaceComCanonicalHudProxyClass))
#define HUD_IFACE_IS_COM_CANONICAL_HUD_PROXY(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), HUD_IFACE_TYPE_COM_CANONICAL_HUD_PROXY))
#define HUD_IFACE_IS_COM_CANONICAL_HUD_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), HUD_IFACE_TYPE_COM_CANONICAL_HUD_PROXY))

typedef struct _HudIfaceComCanonicalHudProxy HudIfaceComCanonicalHudProxy;
typedef struct _HudIfaceComCanonicalHudProxyClass HudIfaceComCanonicalHudProxyClass;
typedef struct _HudIfaceComCanonicalHudProxyPrivate HudIfaceComCanonicalHudProxyPrivate;

struct _HudIfaceComCanonicalHudProxy
{
  /*< private >*/
  GDBusProxy parent_instance;
  HudIfaceComCanonicalHudProxyPrivate *priv;
};

struct _HudIfaceComCanonicalHudProxyClass
{
  GDBusProxyClass parent_class;
};

GType hud_iface_com_canonical_hud_proxy_get_type (void) G_GNUC_CONST;

void hud_iface_com_canonical_hud_proxy_new (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data);
HudIfaceComCanonicalHud *hud_iface_com_canonical_hud_proxy_new_finish (
    GAsyncResult        *res,
    GError             **error);
HudIfaceComCanonicalHud *hud_iface_com_canonical_hud_proxy_new_sync (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error);

void hud_iface_com_canonical_hud_proxy_new_for_bus (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data);
HudIfaceComCanonicalHud *hud_iface_com_canonical_hud_proxy_new_for_bus_finish (
    GAsyncResult        *res,
    GError             **error);
HudIfaceComCanonicalHud *hud_iface_com_canonical_hud_proxy_new_for_bus_sync (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error);


/* ---- */

#define HUD_IFACE_TYPE_COM_CANONICAL_HUD_SKELETON (hud_iface_com_canonical_hud_skeleton_get_type ())
#define HUD_IFACE_COM_CANONICAL_HUD_SKELETON(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), HUD_IFACE_TYPE_COM_CANONICAL_HUD_SKELETON, HudIfaceComCanonicalHudSkeleton))
#define HUD_IFACE_COM_CANONICAL_HUD_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), HUD_IFACE_TYPE_COM_CANONICAL_HUD_SKELETON, HudIfaceComCanonicalHudSkeletonClass))
#define HUD_IFACE_COM_CANONICAL_HUD_SKELETON_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), HUD_IFACE_TYPE_COM_CANONICAL_HUD_SKELETON, HudIfaceComCanonicalHudSkeletonClass))
#define HUD_IFACE_IS_COM_CANONICAL_HUD_SKELETON(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), HUD_IFACE_TYPE_COM_CANONICAL_HUD_SKELETON))
#define HUD_IFACE_IS_COM_CANONICAL_HUD_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), HUD_IFACE_TYPE_COM_CANONICAL_HUD_SKELETON))

typedef struct _HudIfaceComCanonicalHudSkeleton HudIfaceComCanonicalHudSkeleton;
typedef struct _HudIfaceComCanonicalHudSkeletonClass HudIfaceComCanonicalHudSkeletonClass;
typedef struct _HudIfaceComCanonicalHudSkeletonPrivate HudIfaceComCanonicalHudSkeletonPrivate;

struct _HudIfaceComCanonicalHudSkeleton
{
  /*< private >*/
  GDBusInterfaceSkeleton parent_instance;
  HudIfaceComCanonicalHudSkeletonPrivate *priv;
};

struct _HudIfaceComCanonicalHudSkeletonClass
{
  GDBusInterfaceSkeletonClass parent_class;
};

GType hud_iface_com_canonical_hud_skeleton_get_type (void) G_GNUC_CONST;

HudIfaceComCanonicalHud *hud_iface_com_canonical_hud_skeleton_new (void);


G_END_DECLS

#endif /* __HUD_IFACE_H__ */
